// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Community.UmbraDesktop.Services.Arcade.Data;

#nullable disable

namespace Umbraco.Community.UmbraDesktop.Services.Arcade.Data.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerArcadeDbContext))]
    [Migration("20261002142045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeBeatenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ByUserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AtUtc");

                    b.HasIndex("ByUserKey");

                    b.HasIndex("UserKey", "Game", "Board")
                        .IsUnique();

                    b.ToTable("umbraDesktopArcadeBeaten", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeLeaderboardEntity", b =>
                {
                    b.Property<string>("Game")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Board")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Better")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("Max")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min")
                        .HasColumnType("bigint");

                    b.HasKey("Game", "Board");

                    b.ToTable("umbraDesktopArcadeLeaderboard", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeProfileEntity", b =>
                {
                    b.Property<Guid>("UserKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AskedAboutPublic")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyWhenBeaten")
                        .HasColumnType("bit");

                    b.HasKey("UserKey");

                    b.ToTable("umbraDesktopArcadeProfile", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Game", "Board");

                    b.HasIndex("UserKey", "Game", "Board")
                        .IsUnique();

                    b.ToTable("umbraDesktopArcadeScore", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
