/**
 * English (en) strings for the `umbraDesktopAccessories` area.
 *
 * This package's own dictionary, and only this package's: the `accessories` launcher group's
 * heading belongs to the host and ships there, per the group contract in `docs/desktop-apps.md` §6.
 * What lives here is each app's name, which its manifest points at through `meta.label`, and
 * everything the apps themselves say.
 *
 * The elements pass each key to `localize.termOrDefault` with the same English as its fallback, so a
 * backoffice where this dictionary failed to load renders words rather than raw tokens. The
 * duplication is deliberate: the dictionary wins when it is there, and these are the strings the
 * Dutch file translates.
 */
export default {
  umbraDesktopAccessories: {
    // The window titles, taskbar labels and launcher tile text, all from meta.label.
    notepad: 'Notepad',
    paint: 'Paint',
    calculator: 'Calculator',
    clock: 'Clock',
    screensaver: 'Screen Saver',
    charactermap: 'Character Map',
    diskcleanup: 'Disk Cleanup',
    systeminfo: 'System Information',
    // Notepad.
    notepadNew: 'New',
    notepadOpen: 'Open…',
    notepadSave: 'Save',
    notepadWordWrap: 'Word wrap',
    notepadUntitled: 'Untitled',
    notepadLine: 'Ln',
    notepadColumn: 'Col',
    notepadCharacters: 'characters',
    // Paint.
    paintPencil: 'Pencil',
    paintBrush: 'Brush',
    paintEraser: 'Eraser',
    paintFill: 'Fill',
    paintSize: 'Size',
    paintUndo: 'Undo',
    paintNew: 'New',
    paintSave: 'Save',
    paintUntitled: 'Untitled',
    paintCanvas: 'Picture',
    paintForeground: 'Foreground',
    paintBackground: 'Background',
    // Sticky Notes. The board is shared by everyone who uses the desktop.
    stickynotes: 'Sticky Notes',
    stickyNotesNew: 'New note',
    stickyNotesShared: 'Shared with everyone who uses this desktop',
    stickyNotesOffline: 'Cannot reach the board. Your notes are kept and will be saved when it is back.',
    stickyNotesEmpty: 'No notes yet. Add one and everyone who uses this desktop will see it.',
    stickyNotesNote: 'Note by %0%',
    stickyNotesUnsaved: 'Not saved yet',
    stickyNotesDelete: 'Delete note',
    stickyNotesDeleteHeadline: 'Delete this note?',
    stickyNotesDeleteQuestion: 'It is deleted for everyone who uses this desktop.',
    stickyNotesConflict: '%0% changed this note while you were editing it.',
    stickyNotesUseTheirs: 'Use theirs',
    stickyNotesKeepMine: 'Keep mine',
    stickyNotesDeletedElsewhere: 'Someone deleted this note while you were editing it.',
    stickyNotesRestore: 'Put it back',
    stickyNotesDiscard: 'Discard',
    stickyNotesColour_yellow: 'Yellow',
    stickyNotesColour_green: 'Green',
    stickyNotesColour_pink: 'Pink',
    stickyNotesColour_purple: 'Purple',
    stickyNotesColour_blue: 'Blue',
    // Opening and saving, shared by Notepad and Paint. Every file lives in the media library.
    openTitle: 'Open from the media library (Ctrl+O)',
    saveTitle: 'Save to the media library (Ctrl+S)',
    documentName: 'Name',
    savedToMedia: 'Saved to the media library.',
    saveFailed: 'Not saved. %0%',
    openFailed: '%0% could not be read.',
    notepadNotText: 'Notepad opens text files, and %0% is not one.',
    paintNotImage: 'Paint edits pictures, and %0% is not one it can edit.',
    paintTooLarge: '%0% is too large for Paint, which opens pictures up to %1% pixels across.',
    // The Accessories category of Desktop settings.
    settingsCategory: 'Accessories',
    settingsCategoryAbout: 'Where new Notepad and Paint files are saved',
    settingsSaveTo: 'Save new files to',
    settingsSaveToAbout: 'Where Notepad and Paint put a file the first time it is saved. A file opened from the media library is saved back where it is.',
    settingsMediaRoot: 'Media library root',
    settingsChooseFolder: 'Choose folder…',
    settingsUseRoot: 'Use the root',
    // Screen Saver, in Windows 98's words where it had them.
    screensaverChoose: 'Screen saver',
    screensaverNone: '(None)',
    screensaverStarfield: 'Starfield',
    screensaverMystify: 'Mystify',
    screensaverFlying: 'Flying Umbraco',
    screensaverPreview: 'Preview',
    screensaverWait: 'Wait',
    screensaverMinutes: 'minutes',
    screensaverAbout: 'Starts when the desktop has been left alone for the wait. Any key, click or real movement of the mouse brings it back.',
    // Calculator. The key names are what a screen reader says for a key whose face is a symbol,
    // and they follow the Windows calculator's own wording.
    calculatorAdd: 'Plus',
    calculatorSubtract: 'Minus',
    calculatorMultiply: 'Multiply by',
    calculatorDivide: 'Divide by',
    calculatorEquals: 'Equals',
    calculatorPercent: 'Percent',
    calculatorDecimal: 'Decimal separator',
    calculatorNegate: 'Positive negative',
    calculatorBackspace: 'Backspace',
    calculatorClear: 'Clear',
    calculatorClearEntry: 'Clear entry',
    calculatorDivideByZero: 'Cannot divide by zero',
    // Character Map. The characters' own names are Unicode's, which are English in every language.
    characterMapFont: 'Font',
    characterMapFontTheme: 'Theme font',
    characterMapFontSerif: 'Serif',
    characterMapFontSans: 'Sans serif',
    characterMapFontMono: 'Monospace',
    characterMapGroup: 'Group',
    characterMapSearch: 'Search',
    characterMapToCopy: 'Characters to copy',
    characterMapSelect: 'Select',
    characterMapCopy: 'Copy',
    characterMapCopied: 'Copied to the clipboard.',
    characterMapCopyFailed: 'Could not copy. Select the characters and press Ctrl+C.',
    characterMapNoResults: 'No character is called that.',
    characterMapKeystroke: 'Keystroke',
    characterMapGroup_basicLatin: 'Basic Latin',
    characterMapGroup_latin1: 'Latin-1 Supplement',
    characterMapGroup_latinExtendedA: 'Latin Extended-A',
    characterMapGroup_greek: 'Greek and Coptic',
    characterMapGroup_cyrillic: 'Cyrillic',
    characterMapGroup_punctuation: 'General Punctuation',
    characterMapGroup_superscripts: 'Superscripts and Subscripts',
    characterMapGroup_currency: 'Currency Symbols',
    characterMapGroup_letterlike: 'Letterlike Symbols',
    characterMapGroup_numberForms: 'Number Forms',
    characterMapGroup_arrows: 'Arrows',
    characterMapGroup_maths: 'Mathematical Operators',
    characterMapGroup_technical: 'Miscellaneous Technical',
    characterMapGroup_boxDrawing: 'Box Drawing',
    characterMapGroup_blockElements: 'Block Elements',
    characterMapGroup_shapes: 'Geometric Shapes',
    characterMapGroup_symbols: 'Miscellaneous Symbols',
    characterMapGroup_dingbats: 'Dingbats',
    // Disk Cleanup. It empties the recycle bins, for good, so every word here errs on the side of plain.
    diskCleanupIntro: 'Disk Cleanup frees space on the server by permanently deleting what is in the recycle bins.',
    diskCleanupFilesToDelete: 'Files to delete',
    diskCleanupDescription: 'Description',
    diskCleanupContent: 'Content recycle bin',
    diskCleanupContentAbout: 'Pages deleted in the Content section, with everything under them. Emptying the bin deletes them for good, for everyone: they cannot be restored afterwards.',
    diskCleanupMedia: 'Media recycle bin',
    diskCleanupMediaAbout: 'Media deleted in the Media section, with its files. Emptying the bin deletes the items and their files for good, for everyone: they cannot be restored afterwards.',
    diskCleanupItem: '1 item',
    diskCleanupItems: '%0% items',
    diskCleanupEmpty: 'Empty',
    diskCleanupNoAccess: 'No access',
    diskCleanupUnreadable: 'Could not be read',
    diskCleanupRefresh: 'Refresh',
    diskCleanupClean: 'Clean up…',
    diskCleanupConfirmHeadline: 'Delete these for good?',
    diskCleanupConfirmQuestion: 'Everything in them, and everything inside that, is deleted permanently, for everyone who uses this site. It cannot be restored.',
    diskCleanupConfirm: 'Delete permanently',
    diskCleanupDone: 'Cleaned up.',
    diskCleanupDenied_content: 'You do not have access to empty the content recycle bin.',
    diskCleanupDenied_media: 'You do not have access to empty the media recycle bin.',
    diskCleanupFailed_content: 'The content recycle bin could not be emptied.',
    diskCleanupFailed_media: 'The media recycle bin could not be emptied.',
    // System Information, in the words of Windows 98's System Properties and System Information.
    systemInfoGeneral: 'General',
    systemInfoDetailsTab: 'Details',
    systemInfoSystem: 'System:',
    systemInfoRegistered: 'Registered to:',
    systemInfoComputer: 'Computer:',
    systemInfoThemeLine: '%0% theme',
    systemInfoBrowserOn: '%0% on %1%',
    systemInfoProcessors: '%0% logical processors',
    systemInfoRam: '%0% RAM',
    systemInfoUnknown: 'Could not be read',
    systemInfoUmbracoUnknown: 'Umbraco (the version could not be read)',
    systemInfoSectionUmbraco: 'Umbraco',
    systemInfoSectionDesktop: 'Desktop',
    systemInfoSectionServer: 'Server',
    systemInfoSectionComputer: 'Computer',
    systemInfoSectionPackages: 'Installed packages',
    systemInfoItem: 'Item',
    systemInfoValue: 'Value',
    systemInfoVersion: 'Version',
    systemInfoAssemblyVersion: 'Assembly version',
    systemInfoRuntimeMode: 'Runtime mode',
    systemInfoServerOffset: 'Server time offset',
    systemInfoDesktopVersion: 'UmbraDesktop',
    systemInfoAccessoriesVersion: 'Accessories',
    systemInfoTheme: 'Theme',
    systemInfoLanguage: 'Backoffice language',
    systemInfoRegisteredTo: 'Registered to',
    systemInfoEmail: 'Email',
    systemInfoDetails: 'Details',
    systemInfoDenied: 'Not available to your account',
    systemInfoSite: 'Site',
    systemInfoBrowser: 'Browser',
    systemInfoOs: 'Operating system',
    systemInfoProcessorCount: 'Processors',
    systemInfoMemory: 'Memory',
    systemInfoGraphics: 'Graphics',
    systemInfoDisplay: 'Display',
    systemInfoColours: 'Colours',
    systemInfoPixelRatio: 'Pixel ratio',
    systemInfoStorage: 'Stored by this site',
    systemInfoStorageOf: '%0% of %1%',
    systemInfoBrowserLanguage: 'Browser language',
    systemInfoTimeZone: 'Time zone',
    systemInfoUptime: 'Up time',
    systemInfoNotReported: 'Not reported by this browser',
    systemInfoCopy: 'Copy all',
    systemInfoCopied: 'Copied to the clipboard.',
    systemInfoCopyFailed: 'Could not copy.',
  },
};
