/**
 * Dutch (nl) strings for the `umbraDesktopAccessories` area. Same keys as `en.ts`, same reasons.
 *
 * The app names are the ones the Dutch Windows shipped: Kladblok and Rekenmachine were translated
 * there, and Paint never was, so it is not here either. A person looks for a tool by the name their
 * own Windows gave it.
 */
export default {
  umbraDesktopAccessories: {
    notepad: 'Kladblok',
    paint: 'Paint',
    calculator: 'Rekenmachine',
    clock: 'Klok',
    notepadNew: 'Nieuw',
    notepadOpen: 'Openen…',
    notepadSave: 'Opslaan',
    notepadWordWrap: 'Terugloop',
    notepadUntitled: 'Naamloos',
    notepadLine: 'Rg',
    notepadColumn: 'Kol',
    notepadCharacters: 'tekens',
    paintPencil: 'Potlood',
    paintBrush: 'Kwast',
    paintEraser: 'Gum',
    paintFill: 'Opvullen',
    paintSize: 'Grootte',
    paintUndo: 'Ongedaan maken',
    paintNew: 'Nieuw',
    paintSave: 'Opslaan',
    paintUntitled: 'Naamloos',
    paintCanvas: 'Afbeelding',
    paintForeground: 'Voorgrond',
    paintBackground: 'Achtergrond',
    stickynotes: 'Plaknotities',
    stickyNotesNew: 'Nieuwe notitie',
    stickyNotesShared: 'Gedeeld met iedereen die dit bureaublad gebruikt',
    stickyNotesOffline: 'Het bord is niet bereikbaar. Je notities blijven bewaard en worden opgeslagen zodra het terug is.',
    stickyNotesEmpty: 'Nog geen notities. Voeg er een toe en iedereen die dit bureaublad gebruikt ziet hem.',
    stickyNotesNote: 'Notitie van %0%',
    stickyNotesUnsaved: 'Nog niet opgeslagen',
    stickyNotesDelete: 'Notitie verwijderen',
    stickyNotesDeleteHeadline: 'Deze notitie verwijderen?',
    stickyNotesDeleteQuestion: 'Hij wordt verwijderd voor iedereen die dit bureaublad gebruikt.',
    stickyNotesConflict: '%0% heeft deze notitie gewijzigd terwijl jij hem bewerkte.',
    stickyNotesUseTheirs: 'Hun versie gebruiken',
    stickyNotesKeepMine: 'Mijn versie houden',
    stickyNotesDeletedElsewhere: 'Iemand heeft deze notitie verwijderd terwijl jij hem bewerkte.',
    stickyNotesRestore: 'Terugzetten',
    stickyNotesDiscard: 'Weggooien',
    stickyNotesColour_yellow: 'Geel',
    stickyNotesColour_green: 'Groen',
    stickyNotesColour_pink: 'Roze',
    stickyNotesColour_purple: 'Paars',
    stickyNotesColour_blue: 'Blauw',
    download: 'Downloaden',
    saveToMedia: 'Opslaan in mediabibliotheek',
    saveTitleComputer: 'Opslaan op deze computer (Ctrl+S)',
    saveTitleMedia: 'Opslaan in de mediabibliotheek (Ctrl+S)',
    savedToMedia: 'Opgeslagen in de mediabibliotheek als %0%.',
    saveToMediaFailed: 'Opslaan in de mediabibliotheek is mislukt',
    settingsCategory: 'Bureau-accessoires',
    settingsCategoryAbout: 'Waar Kladblok en Paint opslaan',
    settingsSaveTo: 'Bestanden van Kladblok en Paint opslaan in',
    settingsSaveToAbout: 'Wat Opslaan en Ctrl+S doen. Elke app houdt een knop voor de andere plek, zodat beide altijd één klik weg zijn.',
    settingsComputer: 'Deze computer',
    settingsComputerAbout: 'Downloadt het bestand, zoals je browser alles opslaat.',
    settingsMedia: 'Mediabibliotheek',
    settingsMediaAbout: 'Slaat het bestand op als media-item. Hetzelfde document opnieuw opslaan werkt dat item bij in plaats van er een toe te voegen.',
    settingsMediaRoot: 'Hoofdmap van de mediabibliotheek',
    settingsChooseFolder: 'Map kiezen…',
    settingsUseRoot: 'Hoofdmap gebruiken',
    calculatorAdd: 'Plus',
    calculatorSubtract: 'Min',
    calculatorMultiply: 'Vermenigvuldigen met',
    calculatorDivide: 'Delen door',
    calculatorEquals: 'Is gelijk aan',
    calculatorPercent: 'Procent',
    calculatorDecimal: 'Decimaalteken',
    calculatorNegate: 'Positief negatief',
    calculatorBackspace: 'Backspace',
    calculatorClear: 'Wissen',
    calculatorClearEntry: 'Invoer wissen',
    calculatorDivideByZero: 'Kan niet delen door nul',
  },
};
