/**
 * Dutch (nl) strings for the `umbraDesktopAccessories` area. Same keys as `en.ts`, same reasons.
 *
 * The app names are the ones the Dutch Windows shipped: Kladblok and Rekenmachine were translated
 * there, and Paint never was, so it is not here either. A person looks for a tool by the name their
 * own Windows gave it.
 */
export default {
  umbraDesktopAccessories: {
    notepad: 'Kladblok',
    paint: 'Paint',
    calculator: 'Rekenmachine',
    clock: 'Klok',
    screensaver: 'Schermbeveiliging',
    charactermap: 'Tekenoverzicht',
    diskcleanup: 'Schijfopruiming',
    systeminfo: 'Systeeminformatie',
    notepadNew: 'Nieuw',
    notepadOpen: 'Openen…',
    notepadSave: 'Opslaan',
    notepadWordWrap: 'Terugloop',
    notepadUntitled: 'Naamloos',
    notepadLine: 'Rg',
    notepadColumn: 'Kol',
    notepadCharacters: 'tekens',
    paintPencil: 'Potlood',
    paintBrush: 'Kwast',
    paintEraser: 'Gum',
    paintFill: 'Opvullen',
    paintSize: 'Grootte',
    paintUndo: 'Ongedaan maken',
    paintNew: 'Nieuw',
    paintSave: 'Opslaan',
    paintUntitled: 'Naamloos',
    paintCanvas: 'Afbeelding',
    paintForeground: 'Voorgrond',
    paintBackground: 'Achtergrond',
    stickynotes: 'Plaknotities',
    stickyNotesNew: 'Nieuwe notitie',
    stickyNotesShared: 'Gedeeld met iedereen die dit bureaublad gebruikt',
    stickyNotesOffline: 'Het bord is niet bereikbaar. Je notities blijven bewaard en worden opgeslagen zodra het terug is.',
    stickyNotesEmpty: 'Nog geen notities. Voeg er een toe en iedereen die dit bureaublad gebruikt ziet hem.',
    stickyNotesNote: 'Notitie van %0%',
    stickyNotesUnsaved: 'Nog niet opgeslagen',
    stickyNotesDelete: 'Notitie verwijderen',
    stickyNotesDeleteHeadline: 'Deze notitie verwijderen?',
    stickyNotesDeleteQuestion: 'Hij wordt verwijderd voor iedereen die dit bureaublad gebruikt.',
    stickyNotesConflict: '%0% heeft deze notitie gewijzigd terwijl jij hem bewerkte.',
    stickyNotesUseTheirs: 'Hun versie gebruiken',
    stickyNotesKeepMine: 'Mijn versie houden',
    stickyNotesDeletedElsewhere: 'Iemand heeft deze notitie verwijderd terwijl jij hem bewerkte.',
    stickyNotesRestore: 'Terugzetten',
    stickyNotesDiscard: 'Weggooien',
    stickyNotesColour_yellow: 'Geel',
    stickyNotesColour_green: 'Groen',
    stickyNotesColour_pink: 'Roze',
    stickyNotesColour_purple: 'Paars',
    stickyNotesColour_blue: 'Blauw',
    openTitle: 'Openen uit de mediabibliotheek (Ctrl+O)',
    saveTitle: 'Opslaan in de mediabibliotheek (Ctrl+S)',
    documentName: 'Naam',
    savedToMedia: 'Opgeslagen in de mediabibliotheek.',
    saveFailed: 'Niet opgeslagen. %0%',
    openFailed: '%0% kon niet worden gelezen.',
    notepadNotText: 'Kladblok opent tekstbestanden, en %0% is er geen.',
    paintNotImage: 'Paint bewerkt afbeeldingen, en %0% is er geen die het kan bewerken.',
    paintTooLarge: '%0% is te groot voor Paint, dat afbeeldingen tot %1% pixels breed opent.',
    settingsCategory: 'Bureau-accessoires',
    settingsCategoryAbout: 'Waar nieuwe bestanden van Kladblok en Paint worden opgeslagen, en de schermbeveiliging',
    settingsSaveTo: 'Nieuwe bestanden opslaan in',
    settingsSaveToAbout: 'Waar Kladblok en Paint een bestand de eerste keer opslaan. Een bestand dat uit de mediabibliotheek is geopend, wordt teruggezet waar het staat.',
    settingsMediaRoot: 'Hoofdmap van de mediabibliotheek',
    settingsChooseFolder: 'Map kiezen…',
    settingsUseRoot: 'Hoofdmap gebruiken',
    settingsScreensaver: 'Schermbeveiliging',
    screensaverChoose: 'Schermbeveiliging',
    screensaverNone: '(Geen)',
    screensaverStarfield: 'Sterrenveld',
    screensaverMystify: 'Mystify',
    screensaverFlying: 'Vliegende Umbraco',
    screensaverPreview: 'Voorbeeld',
    screensaverWait: 'Wachttijd',
    screensaverMinutes: 'minuten',
    screensaverAbout: 'Start als het bureaublad zo lang niet is gebruikt. Een toets, een klik of een echte beweging van de muis brengt het terug.',
    calculatorAdd: 'Plus',
    calculatorSubtract: 'Min',
    calculatorMultiply: 'Vermenigvuldigen met',
    calculatorDivide: 'Delen door',
    calculatorEquals: 'Is gelijk aan',
    calculatorPercent: 'Procent',
    calculatorDecimal: 'Decimaalteken',
    calculatorNegate: 'Positief negatief',
    calculatorBackspace: 'Backspace',
    calculatorClear: 'Wissen',
    calculatorClearEntry: 'Invoer wissen',
    calculatorDivideByZero: 'Kan niet delen door nul',
    // Tekenoverzicht. De namen van de tekens zelf zijn die van Unicode, en die zijn Engels.
    characterMapFont: 'Lettertype',
    characterMapFontTheme: 'Lettertype van het thema',
    characterMapFontSerif: 'Schreef',
    characterMapFontSans: 'Schreefloos',
    characterMapFontMono: 'Vaste breedte',
    characterMapGroup: 'Groep',
    characterMapSearch: 'Zoeken',
    characterMapToCopy: 'Te kopiëren tekens',
    characterMapSelect: 'Selecteren',
    characterMapCopy: 'Kopiëren',
    characterMapCopied: 'Naar het klembord gekopieerd.',
    characterMapCopyFailed: 'Kopiëren lukte niet. Selecteer de tekens en druk op Ctrl+C.',
    characterMapNoResults: 'Geen teken heet zo.',
    characterMapKeystroke: 'Toetsaanslag',
    characterMapGroup_basicLatin: 'Latijn (basis)',
    characterMapGroup_latin1: 'Latijn-1 (aanvulling)',
    characterMapGroup_latinExtendedA: 'Latijn (uitgebreid A)',
    characterMapGroup_greek: 'Grieks en Koptisch',
    characterMapGroup_cyrillic: 'Cyrillisch',
    characterMapGroup_punctuation: 'Leestekens',
    characterMapGroup_superscripts: 'Superscript en subscript',
    characterMapGroup_currency: 'Valutasymbolen',
    characterMapGroup_letterlike: 'Letterachtige symbolen',
    characterMapGroup_numberForms: 'Getalvormen',
    characterMapGroup_arrows: 'Pijlen',
    characterMapGroup_maths: 'Wiskundige operatoren',
    characterMapGroup_technical: 'Diverse technische tekens',
    characterMapGroup_boxDrawing: 'Kaderlijnen',
    characterMapGroup_blockElements: 'Blokken',
    characterMapGroup_shapes: 'Geometrische vormen',
    characterMapGroup_symbols: 'Diverse symbolen',
    characterMapGroup_dingbats: 'Dingbats',
    // Schijfopruiming.
    diskCleanupIntro: 'Schijfopruiming maakt ruimte vrij op de server door wat in de prullenbakken staat definitief te verwijderen.',
    diskCleanupFilesToDelete: 'Te verwijderen bestanden',
    diskCleanupDescription: 'Beschrijving',
    diskCleanupContent: 'Prullenbak van Content',
    diskCleanupContentAbout: 'Pagina\'s die in de sectie Content zijn verwijderd, met alles eronder. Legen verwijdert ze definitief, voor iedereen: ze kunnen daarna niet meer worden teruggezet.',
    diskCleanupMedia: 'Prullenbak van Media',
    diskCleanupMediaAbout: 'Media die in de sectie Media zijn verwijderd, met hun bestanden. Legen verwijdert de items en hun bestanden definitief, voor iedereen: ze kunnen daarna niet meer worden teruggezet.',
    diskCleanupItem: '1 item',
    diskCleanupItems: '%0% items',
    diskCleanupEmpty: 'Leeg',
    diskCleanupNoAccess: 'Geen toegang',
    diskCleanupUnreadable: 'Kon niet worden gelezen',
    diskCleanupRefresh: 'Vernieuwen',
    diskCleanupClean: 'Opruimen…',
    diskCleanupConfirmHeadline: 'Deze definitief verwijderen?',
    diskCleanupConfirmQuestion: 'Alles erin, en alles daaronder, wordt definitief verwijderd, voor iedereen die deze site gebruikt. Het kan niet worden teruggezet.',
    diskCleanupConfirm: 'Definitief verwijderen',
    diskCleanupDone: 'Opgeruimd.',
    diskCleanupDenied_content: 'Je hebt geen toegang om de prullenbak van Content te legen.',
    diskCleanupDenied_media: 'Je hebt geen toegang om de prullenbak van Media te legen.',
    diskCleanupFailed_content: 'De prullenbak van Content kon niet worden geleegd.',
    diskCleanupFailed_media: 'De prullenbak van Media kon niet worden geleegd.',
    // Systeeminformatie, in de woorden van Systeemeigenschappen in Windows 98.
    systemInfoGeneral: 'Algemeen',
    systemInfoDetailsTab: 'Details',
    systemInfoSystem: 'Systeem:',
    systemInfoRegistered: 'Geregistreerd op naam van:',
    systemInfoComputer: 'Computer:',
    systemInfoThemeLine: 'Thema %0%',
    systemInfoBrowserOn: '%0% op %1%',
    systemInfoProcessors: '%0% logische processors',
    systemInfoRam: '%0% RAM',
    systemInfoUnknown: 'Kon niet worden gelezen',
    systemInfoUmbracoUnknown: 'Umbraco (de versie kon niet worden gelezen)',
    systemInfoSectionUmbraco: 'Umbraco',
    systemInfoSectionDesktop: 'Bureaublad',
    systemInfoSectionServer: 'Server',
    systemInfoSectionComputer: 'Computer',
    systemInfoSectionPackages: 'Geïnstalleerde pakketten',
    systemInfoItem: 'Item',
    systemInfoValue: 'Waarde',
    systemInfoVersion: 'Versie',
    systemInfoAssemblyVersion: 'Assemblyversie',
    systemInfoRuntimeMode: 'Runtimemodus',
    systemInfoServerOffset: 'Tijdverschil van de server',
    systemInfoDesktopVersion: 'UmbraDesktop',
    systemInfoAccessoriesVersion: 'Bureau-accessoires',
    systemInfoTheme: 'Thema',
    systemInfoLanguage: 'Taal van de backoffice',
    systemInfoRegisteredTo: 'Geregistreerd op naam van',
    systemInfoEmail: 'E-mail',
    systemInfoDetails: 'Details',
    systemInfoDenied: 'Niet beschikbaar voor je account',
    systemInfoSite: 'Site',
    systemInfoBrowser: 'Browser',
    systemInfoOs: 'Besturingssysteem',
    systemInfoProcessorCount: 'Processors',
    systemInfoMemory: 'Geheugen',
    systemInfoGraphics: 'Grafische kaart',
    systemInfoDisplay: 'Beeldscherm',
    systemInfoColours: 'Kleuren',
    systemInfoPixelRatio: 'Pixelverhouding',
    systemInfoStorage: 'Opgeslagen door deze site',
    systemInfoStorageOf: '%0% van %1%',
    systemInfoBrowserLanguage: 'Taal van de browser',
    systemInfoTimeZone: 'Tijdzone',
    systemInfoUptime: 'Actief sinds',
    systemInfoNotReported: 'Niet gemeld door deze browser',
    systemInfoCopy: 'Alles kopiëren',
    systemInfoCopied: 'Naar het klembord gekopieerd.',
    systemInfoCopyFailed: 'Kopiëren lukte niet.',
  },
};
