/**
 * Dutch (nl) strings for the `umbraDesktopAccessories` area. Same keys as `en.ts`, same reasons.
 *
 * The app names are the ones the Dutch Windows shipped: Kladblok and Rekenmachine were translated
 * there, and Paint never was, so it is not here either. A person looks for a tool by the name their
 * own Windows gave it.
 */
export default {
  umbraDesktopAccessories: {
    notepad: 'Kladblok',
    paint: 'Paint',
    calculator: 'Rekenmachine',
    clock: 'Klok',
    screensaver: 'Schermbeveiliging',
    notepadNew: 'Nieuw',
    notepadOpen: 'Openen…',
    notepadSave: 'Opslaan',
    notepadWordWrap: 'Terugloop',
    notepadUntitled: 'Naamloos',
    notepadLine: 'Rg',
    notepadColumn: 'Kol',
    notepadCharacters: 'tekens',
    paintPencil: 'Potlood',
    paintBrush: 'Kwast',
    paintEraser: 'Gum',
    paintFill: 'Opvullen',
    paintSize: 'Grootte',
    paintUndo: 'Ongedaan maken',
    paintNew: 'Nieuw',
    paintSave: 'Opslaan',
    paintUntitled: 'Naamloos',
    paintCanvas: 'Afbeelding',
    paintForeground: 'Voorgrond',
    paintBackground: 'Achtergrond',
    stickynotes: 'Plaknotities',
    stickyNotesNew: 'Nieuwe notitie',
    stickyNotesShared: 'Gedeeld met iedereen die dit bureaublad gebruikt',
    stickyNotesOffline: 'Het bord is niet bereikbaar. Je notities blijven bewaard en worden opgeslagen zodra het terug is.',
    stickyNotesEmpty: 'Nog geen notities. Voeg er een toe en iedereen die dit bureaublad gebruikt ziet hem.',
    stickyNotesNote: 'Notitie van %0%',
    stickyNotesUnsaved: 'Nog niet opgeslagen',
    stickyNotesDelete: 'Notitie verwijderen',
    stickyNotesDeleteHeadline: 'Deze notitie verwijderen?',
    stickyNotesDeleteQuestion: 'Hij wordt verwijderd voor iedereen die dit bureaublad gebruikt.',
    stickyNotesConflict: '%0% heeft deze notitie gewijzigd terwijl jij hem bewerkte.',
    stickyNotesUseTheirs: 'Hun versie gebruiken',
    stickyNotesKeepMine: 'Mijn versie houden',
    stickyNotesDeletedElsewhere: 'Iemand heeft deze notitie verwijderd terwijl jij hem bewerkte.',
    stickyNotesRestore: 'Terugzetten',
    stickyNotesDiscard: 'Weggooien',
    stickyNotesColour_yellow: 'Geel',
    stickyNotesColour_green: 'Groen',
    stickyNotesColour_pink: 'Roze',
    stickyNotesColour_purple: 'Paars',
    stickyNotesColour_blue: 'Blauw',
    openTitle: 'Openen uit de mediabibliotheek (Ctrl+O)',
    saveTitle: 'Opslaan in de mediabibliotheek (Ctrl+S)',
    documentName: 'Naam',
    savedToMedia: 'Opgeslagen in de mediabibliotheek.',
    saveFailed: 'Niet opgeslagen. %0%',
    openFailed: '%0% kon niet worden gelezen.',
    notepadNotText: 'Kladblok opent tekstbestanden, en %0% is er geen.',
    paintNotImage: 'Paint bewerkt afbeeldingen, en %0% is er geen die het kan bewerken.',
    paintTooLarge: '%0% is te groot voor Paint, dat afbeeldingen tot %1% pixels breed opent.',
    settingsCategory: 'Bureau-accessoires',
    settingsCategoryAbout: 'Waar nieuwe bestanden van Kladblok en Paint worden opgeslagen, en de schermbeveiliging',
    settingsSaveTo: 'Nieuwe bestanden opslaan in',
    settingsSaveToAbout: 'Waar Kladblok en Paint een bestand de eerste keer opslaan. Een bestand dat uit de mediabibliotheek is geopend, wordt teruggezet waar het staat.',
    settingsMediaRoot: 'Hoofdmap van de mediabibliotheek',
    settingsChooseFolder: 'Map kiezen…',
    settingsUseRoot: 'Hoofdmap gebruiken',
    settingsScreensaver: 'Schermbeveiliging',
    screensaverChoose: 'Schermbeveiliging',
    screensaverNone: '(Geen)',
    screensaverStarfield: 'Sterrenveld',
    screensaverMystify: 'Mystify',
    screensaverFlying: 'Vliegende Umbraco',
    screensaverPreview: 'Voorbeeld',
    screensaverWait: 'Wachttijd',
    screensaverMinutes: 'minuten',
    screensaverAbout: 'Start als het bureaublad zo lang niet is gebruikt. Een toets, een klik of een echte beweging van de muis brengt het terug.',
    calculatorAdd: 'Plus',
    calculatorSubtract: 'Min',
    calculatorMultiply: 'Vermenigvuldigen met',
    calculatorDivide: 'Delen door',
    calculatorEquals: 'Is gelijk aan',
    calculatorPercent: 'Procent',
    calculatorDecimal: 'Decimaalteken',
    calculatorNegate: 'Positief negatief',
    calculatorBackspace: 'Backspace',
    calculatorClear: 'Wissen',
    calculatorClearEntry: 'Invoer wissen',
    calculatorDivideByZero: 'Kan niet delen door nul',
  },
};
