"""Writes src/character-map/unicode-data.ts: the characters Character Map shows, with their names.

Browsers have no API for a character's Unicode name, and Character Map's status bar and search both
need one, so the names are generated here, once, from Python's own copy of the Unicode Character
Database, and committed. Run it again (python3 scripts/character-map-data.py, from backoffice/) to
change the blocks or pick up a newer Unicode; nothing in the build runs it.

The blocks are the ones a person writing web content reaches for, in Unicode's order: letters with
accents, punctuation, currency, arrows, maths, box drawing, symbols. Emoji are left out: every
device already has a picker for those, and they would triple the file.
"""

import unicodedata
from pathlib import Path

# (id, first, last). The id is also the dictionary key suffix for the block's name.
BLOCKS = [
    ("basicLatin", 0x0020, 0x007E),
    ("latin1", 0x00A0, 0x00FF),
    ("latinExtendedA", 0x0100, 0x017F),
    ("greek", 0x0370, 0x03FF),
    ("cyrillic", 0x0400, 0x04FF),
    ("punctuation", 0x2000, 0x206F),
    ("superscripts", 0x2070, 0x209F),
    ("currency", 0x20A0, 0x20CF),
    ("letterlike", 0x2100, 0x214F),
    ("numberForms", 0x2150, 0x218F),
    ("arrows", 0x2190, 0x21FF),
    ("maths", 0x2200, 0x22FF),
    ("technical", 0x2300, 0x23FF),
    ("boxDrawing", 0x2500, 0x257F),
    ("blockElements", 0x2580, 0x259F),
    ("shapes", 0x25A0, 0x25FF),
    ("symbols", 0x2600, 0x26FF),
    ("dingbats", 0x2700, 0x27BF),
]

# The categories that are not a character you can see on its own.
SKIPPED = {"Cc", "Cs", "Co", "Cn", "Zl", "Zp"}


def entries(first, last):
    for code in range(first, last + 1):
        char = chr(code)
        name = unicodedata.name(char, "")
        category = unicodedata.category(char)
        if not name or category in SKIPPED:
            continue
        combining = category in ("Mn", "Me")
        yield code, name, combining


def alt_codes():
    """Windows' Alt+0nnn keystrokes: the ANSI code page, Windows-1252, from 0x80 to 0xFF."""
    codes = {}
    for byte in range(0x80, 0x100):
        try:
            char = bytes([byte]).decode("cp1252")
        except UnicodeDecodeError:
            continue
        codes[ord(char)] = byte
    return codes


def main():
    lines = [
        "// Generated by scripts/character-map-data.py from the Unicode Character Database",
        f"// {unicodedata.unidata_version}. Do not edit by hand: change the script and run it again.",
        "",
        "/** The Unicode version the names below come from. */",
        f"export const CHARACTER_MAP_UNICODE_VERSION = '{unicodedata.unidata_version}';",
        "",
        "/**",
        " * Each block's characters: its code point, its Unicode name, and 1 when it is a combining mark",
        " * that draws on the character before it rather than on its own.",
        " */",
        "export const CHARACTER_MAP_BLOCKS: ReadonlyArray<{",
        "  id: string;",
        "  characters: ReadonlyArray<readonly [number, string] | readonly [number, string, 1]>;",
        "}> = [",
    ]
    for block_id, first, last in BLOCKS:
        lines.append(f"  {{ id: '{block_id}', characters: [")
        for code, name, combining in entries(first, last):
            extra = ", 1" if combining else ""
            lines.append(f"    [0x{code:04X}, '{name}'{extra}],")
        lines.append("  ] },")
    lines.append("];")
    lines.append("")
    lines.append("/** Windows' Alt+0nnn keystroke for a character, by code point, where it has one. */")
    lines.append("export const CHARACTER_MAP_ALT_CODES: Readonly<Record<number, number>> = {")
    for code, byte in sorted(alt_codes().items()):
        lines.append(f"  0x{code:04X}: {byte},")
    lines.append("};")
    lines.append("")
    out = Path(__file__).resolve().parent.parent / "src" / "character-map" / "unicode-data.ts"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
