# Pipeline version: 1.2.0

name: $(Date:yyyyMMdd)$(Rev:r)

trigger: 
  branches:
    include:
    - develop
    - "*/develop"
    - release/*
    - "*/release/*"
    - hotfix/*
    - "*/hotfix/*"
    - support/*
    - "*/support/*"
    - main
    - "*/main"

extends:
  template: base/pipeline-base.yml
  parameters:

    # Determines of the pipeline should deploy the package(s) to the NuGet feed of ProudNerds
    publishToProudNerdsNuGetFeed: true
    