using Umbraco.Cms.Core.Media;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Routing;

namespace Umbraco.Community.UmbraDesktop.Manifest;

/// <summary>
/// Builds the manifest's icon entries for each mode.
/// </summary>
/// <param name="publishedUrlProvider">Resolves a media key to the media's own URL.</param>
/// <param name="imageUrlGenerator">Renders that URL at a given size.</param>
public sealed class AppIconSetFactory(
    IPublishedUrlProvider publishedUrlProvider,
    IImageUrlGenerator imageUrlGenerator) : IAppIconSetFactory
{
    /// <summary>
    /// Where the rendered PNGs are served from.
    /// </summary>
    /// <remarks>
    /// Must match the output of <c>backoffice/scripts/build-appicons.mjs</c>, which writes into
    /// vite's <c>public/appicons/</c> and is copied to this path by the build.
    /// </remarks>
    private const string IconBase = "/App_Plugins/Umbraco.Community.UmbraDesktop/appicons";

    /// <inheritdoc />
    public IReadOnlyList<WebAppManifestIcon> Create(AppIconSource source) => source.Mode switch
    {
        AppIconMode.Custom when source.MediaKey is { } key && MediaUrl(key) is { } mediaUrl =>
        [
            new(Resized(mediaUrl, 192), "192x192", "image/png", null),
            new(Resized(mediaUrl, 512), "512x512", "image/png", null),
        ],

        // Default; and Custom whose media is missing or since deleted. The resolver already turns
        // Custom-with-no-key into Default, but it cannot know the key still resolves to something —
        // and an empty icons array is a manifest that is not installable at all, so losing the
        // picture must never cost the install.
        _ => Shipped(),
    };

    /// <summary>
    /// The icon set shipped with the package.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The mark has no background of its own: every platform that shows an installed app supplies
    /// its own container, and painting a tile would nest one container inside another — which is
    /// what makes an icon look imported rather than native.
    /// </para>
    /// <para>
    /// The third entry is a genuinely different drawing rather than the second re-exported. The
    /// ordinary icon runs nearly to the edge of its box, because a taskbar draws it at the size of
    /// that box and artwork that stops short is simply a smaller icon than everything beside it. The
    /// maskable one stops on the safe boundary instead, since it is the render a launcher may crop.
    /// Collapsing the two into one file cost exactly that: a visibly undersized logo on the taskbar.
    /// </para>
    /// </remarks>
    /// <returns>The shipped entries.</returns>
    private static IReadOnlyList<WebAppManifestIcon> Shipped() =>
    [
        new($"{IconBase}/icon-192.png", "192x192", "image/png", null),
        new($"{IconBase}/icon-512.png", "512x512", "image/png", null),
        new($"{IconBase}/icon-512-maskable.png", "512x512", "image/png", "maskable"),
    ];

    /// <summary>
    /// The media item's own URL, as Umbraco resolves it.
    /// </summary>
    /// <remarks>
    /// Asked for rather than assembled, and this matters even before any processing: the media file
    /// system is an abstraction, and a site using Azure Blob Storage resolves media completely
    /// differently from one on local disk. A hand-built <c>/media/...</c> path is a local-disk
    /// assumption that breaks silently everywhere else.
    /// </remarks>
    /// <param name="key">The chosen media item.</param>
    /// <returns>The URL, or null when the item has gone.</returns>
    private string? MediaUrl(Guid key)
    {
        var url = publishedUrlProvider.GetMediaUrl(key);
        return string.IsNullOrWhiteSpace(url) ? null : url;
    }

    /// <summary>
    /// One square render of a media URL, generated by Umbraco.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="IImageUrlGenerator"/> and never string concatenation. Umbraco 17 HMAC-signs
    /// processed image URLs, and ImageSharp's middleware rejects an unsigned one with an empty 400
    /// before it reaches anything — a signature is applied here for free and cannot be by hand.
    /// </para>
    /// <para>
    /// A signed URL is still anonymous, which is what this feature needs: the manifest is read by
    /// machinery that has no session. Signing covers the processing parameters so resize requests
    /// cannot be forged against the site; it does not authenticate the caller.
    /// </para>
    /// <para>
    /// No <c>Format</c> is requested. Umbraco picks a sensible output itself, and the fewer
    /// processing commands in the URL the less there is to get wrong.
    /// </para>
    /// </remarks>
    /// <param name="mediaUrl">The media's own URL.</param>
    /// <param name="size">The square edge length in pixels.</param>
    /// <returns>The generated URL, falling back to the unprocessed one.</returns>
    private string Resized(string mediaUrl, int size) =>
        imageUrlGenerator.GetImageUrl(new ImageUrlGenerationOptions(mediaUrl)
        {
            Width = size,
            Height = size,
            // Crop so a non-square upload fills the tile: an icon that does not fill its tile reads
            // as broken, where a crop reads as a crop.
            ImageCropMode = ImageCropMode.Crop,
        }) ?? mediaUrl;
}
