// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateConnectionData, CreateConnectionErrors, CreateConnectionResponses, DeleteConnectionData, DeleteConnectionErrors, DeleteConnectionResponses, GetAppIdentityData, GetAppIdentityErrors, GetAppIdentityResponses, GetBackgroundJobsData, GetBackgroundJobsErrors, GetBackgroundJobsResponses, GetConnectionsData, GetConnectionsErrors, GetConnectionsResponses, GetConnectionStatusData, GetConnectionStatusErrors, GetConnectionStatusesData, GetConnectionStatusesErrors, GetConnectionStatusesResponses, GetConnectionStatusResponses, SetAppIdentityData, SetAppIdentityErrors, SetAppIdentityResponses, UpdateConnectionData, UpdateConnectionErrors, UpdateConnectionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UmbraDesktopService {
    public static getAppIdentity<ThrowOnError extends boolean = false>(options?: Options<GetAppIdentityData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAppIdentityResponses, GetAppIdentityErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/app-identity',
            ...options
        });
    }
    
    public static setAppIdentity<ThrowOnError extends boolean = false>(options?: Options<SetAppIdentityData, ThrowOnError>) {
        return (options?.client ?? client).post<SetAppIdentityResponses, SetAppIdentityErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/app-identity',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getBackgroundJobs<ThrowOnError extends boolean = false>(options?: Options<GetBackgroundJobsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBackgroundJobsResponses, GetBackgroundJobsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/background-jobs',
            ...options
        });
    }
    
    public static getConnectionStatuses<ThrowOnError extends boolean = false>(options?: Options<GetConnectionStatusesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetConnectionStatusesResponses, GetConnectionStatusesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/connection-status',
            ...options
        });
    }
    
    public static getConnectionStatus<ThrowOnError extends boolean = false>(options: Options<GetConnectionStatusData, ThrowOnError>) {
        return (options.client ?? client).get<GetConnectionStatusResponses, GetConnectionStatusErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/connection-status/{id}',
            ...options
        });
    }
    
    public static getConnections<ThrowOnError extends boolean = false>(options?: Options<GetConnectionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetConnectionsResponses, GetConnectionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/connections',
            ...options
        });
    }
    
    public static createConnection<ThrowOnError extends boolean = false>(options?: Options<CreateConnectionData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateConnectionResponses, CreateConnectionErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/connections',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteConnection<ThrowOnError extends boolean = false>(options: Options<DeleteConnectionData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteConnectionResponses, DeleteConnectionErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/connections/{id}',
            ...options
        });
    }
    
    public static updateConnection<ThrowOnError extends boolean = false>(options: Options<UpdateConnectionData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateConnectionResponses, UpdateConnectionErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/umbradesktop/connections/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
