// This file is auto-generated by @hey-api/openapi-ts

export type AllowedDocumentTypeModel = {
    id: string;
    name: string;
    description?: string | null;
    icon?: string | null;
};

export type AllowedMediaTypeModel = {
    id: string;
    name: string;
    description?: string | null;
    icon?: string | null;
};

export type AuditLogResponseModel = {
    user: ReferenceByIdModel;
    timestamp: string;
    logType: AuditTypeModel;
    comment?: string | null;
    parameters?: string | null;
};

export enum AuditTypeModel {
    NEW = 'New',
    SAVE = 'Save',
    SAVE_VARIANT = 'SaveVariant',
    OPEN = 'Open',
    DELETE = 'Delete',
    PUBLISH = 'Publish',
    PUBLISH_VARIANT = 'PublishVariant',
    SEND_TO_PUBLISH = 'SendToPublish',
    SEND_TO_PUBLISH_VARIANT = 'SendToPublishVariant',
    UNPUBLISH = 'Unpublish',
    UNPUBLISH_VARIANT = 'UnpublishVariant',
    MOVE = 'Move',
    COPY = 'Copy',
    ASSIGN_DOMAIN = 'AssignDomain',
    PUBLIC_ACCESS = 'PublicAccess',
    SORT = 'Sort',
    NOTIFY = 'Notify',
    SYSTEM = 'System',
    ROLL_BACK = 'RollBack',
    PACKAGER_INSTALL = 'PackagerInstall',
    PACKAGER_UNINSTALL = 'PackagerUninstall',
    CUSTOM = 'Custom',
    CONTENT_VERSION_PREVENT_CLEANUP = 'ContentVersionPreventCleanup',
    CONTENT_VERSION_ENABLE_CLEANUP = 'ContentVersionEnableCleanup'
}

export type AvailableDocumentTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
    folderPath: Array<string>;
    isCompatible: boolean;
};

export type AvailableMediaTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
    folderPath: Array<string>;
    isCompatible: boolean;
};

export type AvailableMemberTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
    folderPath: Array<string>;
    isCompatible: boolean;
};

export type CalculatedUserStartNodesResponseModel = {
    id: string;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
};

export type ChangePasswordCurrentUserRequestModel = {
    newPassword: string;
    oldPassword?: string | null;
};

export type ChangePasswordUserRequestModel = {
    newPassword: string;
};

export type CodesModel = {
    icpc?: Array<string> | null;
    access?: string | null;
    medical_source?: Array<string> | null;
};

export enum CompositionTypeModel {
    COMPOSITION = 'Composition',
    INHERITANCE = 'Inheritance'
}

export type ConsentLevelPresentationModel = {
    level: TelemetryLevelModel;
    description: string;
};

export type ContentItemElementSituationModel = {
    title?: string | null;
    value?: string | null;
    link?: ReferencedLinkModel | null;
    downloads?: Array<string> | null;
    url?: VideoUrlsModel | null;
    changed?: string | null;
};

export type ContentSituationModel = {
    index: number;
    type: SituationContentTypeModel;
    category?: string | null;
    uuid: string;
    item?: ContentItemElementSituationModel | null;
};

export type CopyDataTypeRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type CopyDocumentRequestModel = {
    target?: ReferenceByIdModel | null;
    relateToOriginal: boolean;
    includeDescendants: boolean;
};

export type CopyDocumentTypeRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type CopyMediaTypeRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type CreateDataTypeRequestModel = {
    name: string;
    editorAlias: string;
    editorUiAlias: string;
    values: Array<DataTypePropertyPresentationModel>;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
};

export type CreateDictionaryItemRequestModel = {
    name: string;
    translations: Array<DictionaryItemTranslationModel>;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
};

export type CreateDocumentBlueprintFromDocumentRequestModel = {
    document: ReferenceByIdModel;
    id?: string | null;
    name: string;
    parent?: ReferenceByIdModel | null;
};

export type CreateDocumentBlueprintRequestModel = {
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
    documentType: ReferenceByIdModel;
};

export type CreateDocumentRequestModel = {
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
    documentType: ReferenceByIdModel;
    template: ReferenceByIdModel | null;
};

export type CreateDocumentTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type CreateDocumentTypePropertyTypeRequestModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type CreateDocumentTypeRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<CreateDocumentTypePropertyTypeRequestModel>;
    containers: Array<CreateDocumentTypePropertyTypeContainerRequestModel>;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
    allowedTemplates: Array<ReferenceByIdModel>;
    defaultTemplate?: ReferenceByIdModel | null;
    cleanup: DocumentTypeCleanupModel;
    allowedDocumentTypes: Array<DocumentTypeSortModel>;
    compositions: Array<DocumentTypeCompositionModel>;
};

export type CreateFolderRequestModel = {
    name: string;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
};

export type CreateInitialPasswordUserRequestModel = {
    user: ReferenceByIdModel;
    token: string;
    password: string;
};

export type CreateLanguageRequestModel = {
    name: string;
    isDefault: boolean;
    isMandatory: boolean;
    fallbackIsoCode?: string | null;
    isoCode: string;
};

export type CreateMediaRequestModel = {
    values: Array<MediaValueModel>;
    variants: Array<MediaVariantRequestModel>;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
    mediaType: ReferenceByIdModel;
};

export type CreateMediaTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type CreateMediaTypePropertyTypeRequestModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type CreateMediaTypeRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    isElement: boolean;
    properties: Array<CreateMediaTypePropertyTypeRequestModel>;
    containers: Array<CreateMediaTypePropertyTypeContainerRequestModel>;
    id?: string | null;
    parent?: ReferenceByIdModel | null;
    allowedMediaTypes: Array<MediaTypeSortModel>;
    compositions: Array<MediaTypeCompositionModel>;
    collection?: ReferenceByIdModel | null;
};

export type CreateMemberGroupRequestModel = {
    name: string;
    id?: string | null;
};

export type CreateMemberRequestModel = {
    values: Array<MemberValueModel>;
    variants: Array<MemberVariantRequestModel>;
    id?: string | null;
    email: string;
    username: string;
    password: string;
    memberType: ReferenceByIdModel;
    groups?: Array<string> | null;
    isApproved: boolean;
};

export type CreateMemberTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type CreateMemberTypePropertyTypeRequestModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
    isSensitive: boolean;
    visibility: MemberTypePropertyTypeVisibilityModel;
};

export type CreateMemberTypeRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<CreateMemberTypePropertyTypeRequestModel>;
    containers: Array<CreateMemberTypePropertyTypeContainerRequestModel>;
    id?: string | null;
    compositions: Array<MemberTypeCompositionModel>;
};

export type CreatePackageRequestModel = {
    name: string;
    contentNodeId?: string | null;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
    id?: string | null;
};

export type CreatePartialViewFolderRequestModel = {
    name: string;
    parent?: FileSystemFolderModel | null;
};

export type CreatePartialViewRequestModel = {
    name: string;
    parent?: FileSystemFolderModel | null;
    content: string;
};

export type CreateScriptFolderRequestModel = {
    name: string;
    parent?: FileSystemFolderModel | null;
};

export type CreateScriptRequestModel = {
    name: string;
    parent?: FileSystemFolderModel | null;
    content: string;
};

export type CreateStylesheetFolderRequestModel = {
    name: string;
    parent?: FileSystemFolderModel | null;
};

export type CreateStylesheetRequestModel = {
    name: string;
    parent?: FileSystemFolderModel | null;
    content: string;
};

export type CreateTemplateRequestModel = {
    name: string;
    alias: string;
    content?: string | null;
    id?: string | null;
};

export type CreateUserClientCredentialsRequestModel = {
    clientId: string;
    clientSecret: string;
};

export type CreateUserDataRequestModel = {
    group: string;
    identifier: string;
    value: string;
    key?: string | null;
};

export type CreateUserGroupRequestModel = {
    name: string;
    alias: string;
    icon?: string | null;
    sections: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    documentStartNode?: ReferenceByIdModel | null;
    documentRootAccess: boolean;
    mediaStartNode?: ReferenceByIdModel | null;
    mediaRootAccess: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<DocumentPermissionPresentationModel | DocumentPropertyValuePermissionPresentationModel | UnknownTypePermissionPresentationModel>;
    id?: string | null;
};

export type CreateUserRequestModel = {
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
    id?: string | null;
    kind: UserKindModel;
};

export type CreateWebhookRequestModel = {
    enabled: boolean;
    name?: string | null;
    description?: string | null;
    url: string;
    contentTypeKeys: Array<string>;
    headers: {
        [key: string]: string;
    };
    id?: string | null;
    events: Array<string>;
};

export type CultureAndScheduleRequestModel = {
    culture?: string | null;
    schedule?: ScheduleRequestModel | null;
};

export type CultureReponseModel = {
    name: string;
    englishName: string;
};

export type CurrentUserConfigurationResponseModel = {
    keepUserLoggedIn: boolean;
    passwordConfiguration: PasswordConfigurationResponseModel;
    allowChangePassword: boolean;
    allowTwoFactor: boolean;
};

export type CurrentUserResponseModel = {
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
    id: string;
    languageIsoCode: string | null;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
    avatarUrls: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    hasAccessToSensitiveData: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<DocumentPermissionPresentationModel | DocumentPropertyValuePermissionPresentationModel | UnknownTypePermissionPresentationModel>;
    allowedSections: Array<string>;
    isAdmin: boolean;
};

export enum DataTypeChangeModeModel {
    TRUE = 'True',
    FALSE = 'False',
    FALSE_WITH_HELP_TEXT = 'FalseWithHelpText'
}

export type DataTypeContentTypeReferenceModel = {
    id: string;
    type: string | null;
    name: string | null;
    icon: string | null;
};

export type DataTypeItemResponseModel = {
    id: string;
    name: string;
    editorUiAlias?: string | null;
    editorAlias: string;
    isDeletable: boolean;
};

export type DataTypePropertyPresentationModel = {
    alias: string;
    value?: unknown;
};

export type DataTypePropertyReferenceModel = {
    name: string;
    alias: string;
};

export type DataTypeReferenceResponseModel = {
    contentType: DataTypeContentTypeReferenceModel;
    properties: Array<DataTypePropertyReferenceModel>;
};

export type DataTypeResponseModel = {
    name: string;
    editorAlias: string;
    editorUiAlias: string;
    values: Array<DataTypePropertyPresentationModel>;
    id: string;
    isDeletable: boolean;
    canIgnoreStartNodes: boolean;
};

export type DataTypeTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
    isFolder: boolean;
    editorUiAlias?: string | null;
    isDeletable: boolean;
};

export type DatabaseInstallRequestModel = {
    id: string;
    providerName: string;
    server?: string | null;
    name?: string | null;
    username?: string | null;
    password?: string | null;
    useIntegratedAuthentication: boolean;
    connectionString?: string | null;
    trustServerCertificate: boolean;
};

export type DatabaseSettingsPresentationModel = {
    id: string;
    sortOrder: number;
    displayName: string;
    defaultDatabaseName: string;
    providerName: string;
    isConfigured: boolean;
    requiresServer: boolean;
    serverPlaceholder: string;
    requiresCredentials: boolean;
    supportsIntegratedAuthentication: boolean;
    requiresConnectionTest: boolean;
};

export type DatatypeConfigurationResponseModel = {
    canBeChanged: DataTypeChangeModeModel;
    documentListViewId: string;
    mediaListViewId: string;
};

export type DefaultReferenceResponseModel = {
    $type: string;
    id: string;
    name?: string | null;
    type?: string | null;
    icon?: string | null;
};

export type DeleteUserGroupsRequestModel = {
    userGroupIds: Array<ReferenceByIdModel>;
};

export type DeleteUsersRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type DictionaryItemItemResponseModel = {
    id: string;
    name: string;
};

export type DictionaryItemResponseModel = {
    name: string;
    translations: Array<DictionaryItemTranslationModel>;
    id: string;
};

export type DictionaryItemTranslationModel = {
    isoCode: string;
    translation: string;
};

export type DictionaryOverviewResponseModel = {
    name?: string | null;
    id: string;
    parent?: ReferenceByIdModel | null;
    translatedIsoCodes: Array<string>;
};

export enum DirectionModel {
    ASCENDING = 'Ascending',
    DESCENDING = 'Descending'
}

export type DisableUserRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type DocumentBlueprintItemResponseModel = {
    id: string;
    name: string;
    documentType: DocumentTypeReferenceResponseModel;
};

export type DocumentBlueprintResponseModel = {
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
    id: string;
    documentType: DocumentTypeReferenceResponseModel;
};

export type DocumentBlueprintTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
    isFolder: boolean;
    documentType?: DocumentTypeReferenceResponseModel | null;
};

export type DocumentCollectionResponseModel = {
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
    id: string;
    creator?: string | null;
    sortOrder: number;
    documentType: DocumentTypeCollectionReferenceResponseModel;
    isTrashed: boolean;
    isProtected: boolean;
    ancestors: Array<ReferenceByIdModel>;
    updater?: string | null;
};

export type DocumentConfigurationResponseModel = {
    disableDeleteWhenReferenced: boolean;
    disableUnpublishWhenReferenced: boolean;
    allowEditInvariantFromNonDefault: boolean;
    allowNonExistingSegmentsCreation: boolean;
};

export type DocumentItemResponseModel = {
    id: string;
    isTrashed: boolean;
    isProtected: boolean;
    parent?: ReferenceByIdModel | null;
    hasChildren: boolean;
    documentType: DocumentTypeReferenceResponseModel;
    variants: Array<DocumentVariantItemResponseModel>;
};

export type DocumentNotificationResponseModel = {
    actionId: string;
    alias: string;
    subscribed: boolean;
};

export type DocumentPermissionPresentationModel = {
    $type: string;
    document: ReferenceByIdModel;
    verbs: Array<string>;
};

export type DocumentPropertyValuePermissionPresentationModel = {
    $type: string;
    documentType: ReferenceByIdModel;
    propertyType: ReferenceByIdModel;
    verbs: Array<string>;
};

export type DocumentRecycleBinItemResponseModel = {
    id: string;
    createDate: string;
    hasChildren: boolean;
    parent?: ItemReferenceByIdResponseModel | null;
    documentType: DocumentTypeReferenceResponseModel;
    variants: Array<DocumentVariantItemResponseModel>;
};

export type DocumentReferenceResponseModel = {
    $type: string;
    id: string;
    name?: string | null;
    published?: boolean | null;
    documentType: TrackedReferenceDocumentTypeModel;
    variants: Array<DocumentVariantItemResponseModel>;
};

export type DocumentResponseModel = {
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
    id: string;
    documentType: DocumentTypeReferenceResponseModel;
    /**
     * @deprecated
     */
    urls: Array<DocumentUrlInfoModel>;
    template?: ReferenceByIdModel | null;
    isTrashed: boolean;
};

export type DocumentTreeItemResponseModel = {
    hasChildren: boolean;
    parent?: ReferenceByIdModel | null;
    noAccess: boolean;
    isTrashed: boolean;
    id: string;
    createDate: string;
    isProtected: boolean;
    ancestors: Array<ReferenceByIdModel>;
    documentType: DocumentTypeReferenceResponseModel;
    variants: Array<DocumentVariantItemResponseModel>;
};

export type DocumentTypeBlueprintItemResponseModel = {
    id: string;
    name: string;
};

export type DocumentTypeCleanupModel = {
    preventCleanup: boolean;
    keepAllVersionsNewerThanDays?: number | null;
    keepLatestVersionPerDayForDays?: number | null;
};

export type DocumentTypeCollectionReferenceResponseModel = {
    id: string;
    alias: string;
    icon: string;
};

export type DocumentTypeCompositionModel = {
    documentType: ReferenceByIdModel;
    compositionType: CompositionTypeModel;
};

export type DocumentTypeCompositionRequestModel = {
    id?: string | null;
    currentPropertyAliases: Array<string>;
    currentCompositeIds: Array<string>;
    isElement: boolean;
};

export type DocumentTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
};

export type DocumentTypeConfigurationResponseModel = {
    dataTypesCanBeChanged: DataTypeChangeModeModel;
    disableTemplates: boolean;
    useSegments: boolean;
    reservedFieldNames: Array<string>;
};

export type DocumentTypeItemResponseModel = {
    id: string;
    name: string;
    isElement: boolean;
    icon?: string | null;
    description?: string | null;
};

export type DocumentTypePropertyTypeContainerResponseModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type DocumentTypePropertyTypeReferenceResponseModel = {
    $type: string;
    id: string;
    name?: string | null;
    alias?: string | null;
    documentType: TrackedReferenceDocumentTypeModel;
};

export type DocumentTypePropertyTypeResponseModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type DocumentTypeReferenceResponseModel = {
    id: string;
    icon: string;
    collection?: ReferenceByIdModel | null;
};

export type DocumentTypeResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<DocumentTypePropertyTypeResponseModel>;
    containers: Array<DocumentTypePropertyTypeContainerResponseModel>;
    id: string;
    allowedTemplates: Array<ReferenceByIdModel>;
    defaultTemplate?: ReferenceByIdModel | null;
    cleanup: DocumentTypeCleanupModel;
    allowedDocumentTypes: Array<DocumentTypeSortModel>;
    compositions: Array<DocumentTypeCompositionModel>;
};

export type DocumentTypeSortModel = {
    documentType: ReferenceByIdModel;
    sortOrder: number;
};

export type DocumentTypeTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
    isFolder: boolean;
    isElement: boolean;
    icon: string;
};

export type DocumentUrlInfoModel = {
    culture: string | null;
    url: string;
};

export type DocumentUrlInfoResponseModel = {
    id: string;
    urlInfos: Array<DocumentUrlInfoModel>;
};

export type DocumentValueModel = {
    culture?: string | null;
    segment?: string | null;
    alias: string;
    value?: unknown;
};

export type DocumentValueResponseModel = {
    culture?: string | null;
    segment?: string | null;
    alias: string;
    value?: unknown;
    editorAlias: string;
};

export type DocumentVariantItemResponseModel = {
    name: string;
    culture?: string | null;
    state: DocumentVariantStateModel;
};

export type DocumentVariantRequestModel = {
    culture?: string | null;
    segment?: string | null;
    name: string;
};

export type DocumentVariantResponseModel = {
    culture?: string | null;
    segment?: string | null;
    name: string;
    createDate: string;
    updateDate: string;
    state: DocumentVariantStateModel;
    publishDate?: string | null;
    scheduledPublishDate?: string | null;
    scheduledUnpublishDate?: string | null;
};

export enum DocumentVariantStateModel {
    NOT_CREATED = 'NotCreated',
    DRAFT = 'Draft',
    PUBLISHED = 'Published',
    PUBLISHED_PENDING_CHANGES = 'PublishedPendingChanges'
}

export type DocumentVersionItemResponseModel = {
    id: string;
    document: ReferenceByIdModel;
    documentType: ReferenceByIdModel;
    user: ReferenceByIdModel;
    versionDate: string;
    isCurrentPublishedVersion: boolean;
    isCurrentDraftVersion: boolean;
    preventCleanup: boolean;
};

export type DocumentVersionResponseModel = {
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
    id: string;
    documentType: DocumentTypeReferenceResponseModel;
    document?: ReferenceByIdModel | null;
};

export type DomainPresentationModel = {
    domainName: string;
    isoCode: string;
};

export type DomainsResponseModel = {
    defaultIsoCode?: string | null;
    domains: Array<DomainPresentationModel>;
};

export type DynamicRootContextRequestModel = {
    id?: string | null;
    parent: ReferenceByIdModel;
    culture?: string | null;
    segment?: string | null;
};

export type DynamicRootQueryOriginRequestModel = {
    alias: string;
    id?: string | null;
};

export type DynamicRootQueryRequestModel = {
    origin: DynamicRootQueryOriginRequestModel;
    steps: Array<DynamicRootQueryStepRequestModel>;
};

export type DynamicRootQueryStepRequestModel = {
    alias: string;
    documentTypeIds: Array<string>;
};

export type DynamicRootRequestModel = {
    context: DynamicRootContextRequestModel;
    query: DynamicRootQueryRequestModel;
};

export type DynamicRootResponseModel = {
    roots: Array<string>;
};

export type EnableTwoFactorRequestModel = {
    code: string;
    secret: string;
};

export type EnableUserRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type EntityImportAnalysisResponseModel = {
    entityType: string;
    alias?: string | null;
    key?: string | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type FieldPresentationModel = {
    name: string;
    values: Array<string>;
};

export type FileSystemFolderModel = {
    path: string;
};

export type FileSystemTreeItemPresentationModel = {
    hasChildren: boolean;
    name: string;
    path: string;
    parent?: FileSystemFolderModel | null;
    isFolder: boolean;
};

export type FolderResponseModel = {
    name: string;
    id: string;
};

export type HealthCheckActionRequestModel = {
    healthCheck: ReferenceByIdModel;
    alias?: string | null;
    name?: string | null;
    description?: string | null;
    valueRequired: boolean;
    providedValue?: string | null;
    providedValueValidation?: string | null;
    providedValueValidationRegex?: string | null;
    actionParameters?: {
        [key: string]: unknown;
    } | null;
};

export type HealthCheckGroupPresentationModel = {
    name: string;
    checks: Array<HealthCheckModel>;
};

export type HealthCheckGroupResponseModel = {
    name: string;
};

export type HealthCheckGroupWithResultResponseModel = {
    checks: Array<HealthCheckWithResultPresentationModel>;
};

export type HealthCheckModel = {
    id: string;
    name: string;
    description?: string | null;
};

export type HealthCheckResultResponseModel = {
    message: string;
    resultType: StatusResultTypeModel;
    actions?: Array<HealthCheckActionRequestModel> | null;
    readMoreLink?: string | null;
};

export type HealthCheckWithResultPresentationModel = {
    id: string;
    results?: Array<HealthCheckResultResponseModel> | null;
};

export enum HealthStatusModel {
    HEALTHY = 'Healthy',
    UNHEALTHY = 'Unhealthy',
    REBUILDING = 'Rebuilding',
    CORRUPT = 'Corrupt'
}

export type HealthStatusResponseModel = {
    status: HealthStatusModel;
    message?: string | null;
};

export type HelpPageResponseModel = {
    name?: string | null;
    description?: string | null;
    url?: string | null;
    type?: string | null;
};

export enum ImageCropModeModel {
    CROP = 'Crop',
    MAX = 'Max',
    STRETCH = 'Stretch',
    PAD = 'Pad',
    BOX_PAD = 'BoxPad',
    MIN = 'Min'
}

export type ImportDictionaryRequestModel = {
    temporaryFile: ReferenceByIdModel;
    parent?: ReferenceByIdModel | null;
};

export type ImportDocumentTypeRequestModel = {
    file: ReferenceByIdModel;
};

export type ImportMediaTypeRequestModel = {
    file: ReferenceByIdModel;
};

export type IndexResponseModel = {
    name: string;
    healthStatus: HealthStatusResponseModel;
    canRebuild: boolean;
    searcherName: string;
    documentCount: number;
    fieldCount: number;
    providerProperties?: {
        [key: string]: unknown;
    } | null;
};

export type InstallRequestModelReadable = {
    user: UserInstallRequestModelReadable;
    database: DatabaseInstallRequestModel;
    telemetryLevel: TelemetryLevelModel;
};

export type InstallRequestModelWritable = {
    user: UserInstallRequestModelWritable;
    database: DatabaseInstallRequestModel;
    telemetryLevel: TelemetryLevelModel;
};

export type InstallSettingsResponseModel = {
    user: UserSettingsPresentationModel;
    databases: Array<DatabaseSettingsPresentationModel>;
};

export type InviteUserRequestModel = {
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
    id?: string | null;
    message?: string | null;
};

export type ItemReferenceByIdResponseModel = {
    id: string;
};

export type ItemSortingRequestModel = {
    id: string;
    sortOrder: number;
};

export type LanguageItemResponseModel = {
    name: string;
    isoCode: string;
};

export type LanguageResponseModel = {
    name: string;
    isDefault: boolean;
    isMandatory: boolean;
    fallbackIsoCode?: string | null;
    isoCode: string;
};

export type LogLevelCountsReponseModel = {
    information: number;
    debug: number;
    warning: number;
    error: number;
    fatal: number;
};

export enum LogLevelModel {
    VERBOSE = 'Verbose',
    DEBUG = 'Debug',
    INFORMATION = 'Information',
    WARNING = 'Warning',
    ERROR = 'Error',
    FATAL = 'Fatal'
}

export type LogMessagePropertyPresentationModel = {
    name: string;
    value?: string | null;
};

export type LogMessageResponseModel = {
    timestamp: string;
    level: LogLevelModel;
    messageTemplate?: string | null;
    renderedMessage?: string | null;
    properties: Array<LogMessagePropertyPresentationModel>;
    exception?: string | null;
};

export type LogTemplateResponseModel = {
    messageTemplate?: string | null;
    count: number;
};

export type LoggerResponseModel = {
    name: string;
    level: LogLevelModel;
};

export type ManifestResponseModel = {
    name: string;
    id?: string | null;
    version?: string | null;
    extensions: Array<unknown>;
};

export type MediaCollectionResponseModel = {
    values: Array<MediaValueResponseModel>;
    variants: Array<MediaVariantResponseModel>;
    id: string;
    creator?: string | null;
    sortOrder: number;
    mediaType: MediaTypeCollectionReferenceResponseModel;
};

export type MediaConfigurationResponseModel = {
    disableDeleteWhenReferenced: boolean;
    disableUnpublishWhenReferenced: boolean;
};

export type MediaItemResponseModel = {
    id: string;
    isTrashed: boolean;
    parent?: ReferenceByIdModel | null;
    hasChildren: boolean;
    mediaType: MediaTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
};

export type MediaRecycleBinItemResponseModel = {
    id: string;
    createDate: string;
    hasChildren: boolean;
    parent?: ItemReferenceByIdResponseModel | null;
    mediaType: MediaTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
};

export type MediaReferenceResponseModel = {
    $type: string;
    id: string;
    name?: string | null;
    mediaType: TrackedReferenceMediaTypeModel;
};

export type MediaResponseModel = {
    values: Array<MediaValueResponseModel>;
    variants: Array<MediaVariantResponseModel>;
    id: string;
    /**
     * @deprecated
     */
    urls: Array<MediaUrlInfoModel>;
    isTrashed: boolean;
    mediaType: MediaTypeReferenceResponseModel;
};

export type MediaTreeItemResponseModel = {
    hasChildren: boolean;
    parent?: ReferenceByIdModel | null;
    noAccess: boolean;
    isTrashed: boolean;
    id: string;
    createDate: string;
    mediaType: MediaTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
};

export type MediaTypeCollectionReferenceResponseModel = {
    id: string;
    alias: string;
    icon: string;
};

export type MediaTypeCompositionModel = {
    mediaType: ReferenceByIdModel;
    compositionType: CompositionTypeModel;
};

export type MediaTypeCompositionRequestModel = {
    id?: string | null;
    currentPropertyAliases: Array<string>;
    currentCompositeIds: Array<string>;
};

export type MediaTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
};

export type MediaTypeConfigurationResponseModel = {
    reservedFieldNames: Array<string>;
};

export type MediaTypeItemResponseModel = {
    id: string;
    name: string;
    icon?: string | null;
};

export type MediaTypePropertyTypeContainerResponseModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type MediaTypePropertyTypeReferenceResponseModel = {
    $type: string;
    id: string;
    name?: string | null;
    alias?: string | null;
    mediaType: TrackedReferenceMediaTypeModel;
};

export type MediaTypePropertyTypeResponseModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type MediaTypeReferenceResponseModel = {
    id: string;
    icon: string;
    collection?: ReferenceByIdModel | null;
};

export type MediaTypeResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<MediaTypePropertyTypeResponseModel>;
    containers: Array<MediaTypePropertyTypeContainerResponseModel>;
    id: string;
    allowedMediaTypes: Array<MediaTypeSortModel>;
    compositions: Array<MediaTypeCompositionModel>;
    isDeletable: boolean;
    aliasCanBeChanged: boolean;
};

export type MediaTypeSortModel = {
    mediaType: ReferenceByIdModel;
    sortOrder: number;
};

export type MediaTypeTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
    isFolder: boolean;
    icon: string;
    isDeletable: boolean;
};

export type MediaUrlInfoModel = {
    culture: string | null;
    url: string;
};

export type MediaUrlInfoResponseModel = {
    id: string;
    urlInfos: Array<MediaUrlInfoModel>;
};

export type MediaValueModel = {
    culture?: string | null;
    segment?: string | null;
    alias: string;
    value?: unknown;
};

export type MediaValueResponseModel = {
    culture?: string | null;
    segment?: string | null;
    alias: string;
    value?: unknown;
    editorAlias: string;
};

export type MediaVariantRequestModel = {
    culture?: string | null;
    segment?: string | null;
    name: string;
};

export type MediaVariantResponseModel = {
    culture?: string | null;
    segment?: string | null;
    name: string;
    createDate: string;
    updateDate: string;
};

export type MemberConfigurationResponseModel = {
    [key: string]: never;
};

export type MemberGroupItemResponseModel = {
    id: string;
    name: string;
};

export type MemberGroupResponseModel = {
    name: string;
    id: string;
};

export type MemberItemResponseModel = {
    id: string;
    memberType: MemberTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
    kind: MemberKindModel;
};

export enum MemberKindModel {
    DEFAULT = 'Default',
    API = 'Api'
}

export type MemberReferenceResponseModel = {
    $type: string;
    id: string;
    name?: string | null;
    memberType: TrackedReferenceMemberTypeModel;
};

export type MemberResponseModel = {
    values: Array<MemberValueResponseModel>;
    variants: Array<MemberVariantResponseModel>;
    id: string;
    email: string;
    username: string;
    memberType: MemberTypeReferenceResponseModel;
    isApproved: boolean;
    isLockedOut: boolean;
    isTwoFactorEnabled: boolean;
    failedPasswordAttempts: number;
    lastLoginDate?: string | null;
    lastLockoutDate?: string | null;
    lastPasswordChangeDate?: string | null;
    groups: Array<string>;
    kind: MemberKindModel;
};

export type MemberTypeCompositionModel = {
    memberType: ReferenceByIdModel;
    compositionType: CompositionTypeModel;
};

export type MemberTypeCompositionRequestModel = {
    id?: string | null;
    currentPropertyAliases: Array<string>;
    currentCompositeIds: Array<string>;
};

export type MemberTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
};

export type MemberTypeConfigurationResponseModel = {
    reservedFieldNames: Array<string>;
};

export type MemberTypeItemResponseModel = {
    id: string;
    name: string;
    icon?: string | null;
};

export type MemberTypePropertyTypeContainerResponseModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type MemberTypePropertyTypeReferenceResponseModel = {
    $type: string;
    id: string;
    name?: string | null;
    alias?: string | null;
    memberType: TrackedReferenceMemberTypeModel;
};

export type MemberTypePropertyTypeResponseModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
    isSensitive: boolean;
    visibility: MemberTypePropertyTypeVisibilityModel;
};

export type MemberTypePropertyTypeVisibilityModel = {
    memberCanView: boolean;
    memberCanEdit: boolean;
};

export type MemberTypeReferenceResponseModel = {
    id: string;
    icon: string;
    collection?: ReferenceByIdModel | null;
};

export type MemberTypeResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<MemberTypePropertyTypeResponseModel>;
    containers: Array<MemberTypePropertyTypeContainerResponseModel>;
    id: string;
    compositions: Array<MemberTypeCompositionModel>;
};

export type MemberTypeTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
    icon: string;
};

export type MemberValueModel = {
    culture?: string | null;
    segment?: string | null;
    alias: string;
    value?: unknown;
};

export type MemberValueResponseModel = {
    culture?: string | null;
    segment?: string | null;
    alias: string;
    value?: unknown;
    editorAlias: string;
};

export type MemberVariantRequestModel = {
    culture?: string | null;
    segment?: string | null;
    name: string;
};

export type MemberVariantResponseModel = {
    culture?: string | null;
    segment?: string | null;
    name: string;
    createDate: string;
    updateDate: string;
};

export type ModelsBuilderResponseModel = {
    mode: ModelsModeModel;
    canGenerate: boolean;
    outOfDateModels: boolean;
    lastError?: string | null;
    version?: string | null;
    modelsNamespace?: string | null;
    trackingOutOfDateModels: boolean;
};

export enum ModelsModeModel {
    NOTHING = 'Nothing',
    IN_MEMORY_AUTO = 'InMemoryAuto',
    SOURCE_CODE_MANUAL = 'SourceCodeManual',
    SOURCE_CODE_AUTO = 'SourceCodeAuto'
}

export type MoveDataTypeRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type MoveDictionaryRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type MoveDocumentBlueprintRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type MoveDocumentRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type MoveDocumentTypeRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type MoveMediaRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type MoveMediaTypeRequestModel = {
    target?: ReferenceByIdModel | null;
};

export type NamedEntityTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
};

export type NoopSetupTwoFactorModel = {
    [key: string]: never;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type OEmbedResponseModel = {
    markup: string;
};

export type ObjectTypeResponseModel = {
    name?: string | null;
    id: string;
};

export enum OperatorModel {
    EQUALS = 'Equals',
    NOT_EQUALS = 'NotEquals',
    CONTAINS = 'Contains',
    NOT_CONTAINS = 'NotContains',
    LESS_THAN = 'LessThan',
    LESS_THAN_EQUAL_TO = 'LessThanEqualTo',
    GREATER_THAN = 'GreaterThan',
    GREATER_THAN_EQUAL_TO = 'GreaterThanEqualTo'
}

export type OutOfDateStatusResponseModel = {
    status: OutOfDateTypeModel;
};

export enum OutOfDateTypeModel {
    OUT_OF_DATE = 'OutOfDate',
    CURRENT = 'Current',
    UNKNOWN = 'Unknown'
}

export type PackageConfigurationResponseModel = {
    marketplaceUrl: string;
};

export type PackageDefinitionResponseModelReadable = {
    name: string;
    contentNodeId?: string | null;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
    id: string;
    readonly packagePath: string;
};

export type PackageDefinitionResponseModelWritable = {
    name: string;
    contentNodeId?: string | null;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
    id: string;
};

export type PackageMigrationStatusResponseModel = {
    packageName: string;
    hasPendingMigrations: boolean;
};

export type PagedAllowedDocumentTypeModel = {
    total: number;
    items: Array<AllowedDocumentTypeModel>;
};

export type PagedAllowedMediaTypeModel = {
    total: number;
    items: Array<AllowedMediaTypeModel>;
};

export type PagedAuditLogResponseModel = {
    total: number;
    items: Array<AuditLogResponseModel>;
};

export type PagedCultureReponseModel = {
    total: number;
    items: Array<CultureReponseModel>;
};

export type PagedDataTypeItemResponseModel = {
    total: number;
    items: Array<DataTypeItemResponseModel>;
};

export type PagedDataTypeTreeItemResponseModel = {
    total: number;
    items: Array<DataTypeTreeItemResponseModel>;
};

export type PagedDictionaryOverviewResponseModel = {
    total: number;
    items: Array<DictionaryOverviewResponseModel>;
};

export type PagedDocumentBlueprintTreeItemResponseModel = {
    total: number;
    items: Array<DocumentBlueprintTreeItemResponseModel>;
};

export type PagedDocumentCollectionResponseModel = {
    total: number;
    items: Array<DocumentCollectionResponseModel>;
};

export type PagedDocumentRecycleBinItemResponseModel = {
    total: number;
    items: Array<DocumentRecycleBinItemResponseModel>;
};

export type PagedDocumentTreeItemResponseModel = {
    total: number;
    items: Array<DocumentTreeItemResponseModel>;
};

export type PagedDocumentTypeBlueprintItemResponseModel = {
    total: number;
    items: Array<DocumentTypeBlueprintItemResponseModel>;
};

export type PagedDocumentTypeTreeItemResponseModel = {
    total: number;
    items: Array<DocumentTypeTreeItemResponseModel>;
};

export type PagedDocumentVersionItemResponseModel = {
    total: number;
    items: Array<DocumentVersionItemResponseModel>;
};

export type PagedFileSystemTreeItemPresentationModel = {
    total: number;
    items: Array<FileSystemTreeItemPresentationModel>;
};

export type PagedHealthCheckGroupResponseModel = {
    total: number;
    items: Array<HealthCheckGroupResponseModel>;
};

export type PagedHelpPageResponseModel = {
    total: number;
    items: Array<HelpPageResponseModel>;
};

export type PagedIReferenceResponseModel = {
    total: number;
    items: Array<DefaultReferenceResponseModel | DocumentReferenceResponseModel | DocumentTypePropertyTypeReferenceResponseModel | MediaReferenceResponseModel | MediaTypePropertyTypeReferenceResponseModel | MemberReferenceResponseModel | MemberTypePropertyTypeReferenceResponseModel>;
};

export type PagedIndexResponseModel = {
    total: number;
    items: Array<IndexResponseModel>;
};

export type PagedLanguageResponseModel = {
    total: number;
    items: Array<LanguageResponseModel>;
};

export type PagedLogMessageResponseModel = {
    total: number;
    items: Array<LogMessageResponseModel>;
};

export type PagedLogTemplateResponseModel = {
    total: number;
    items: Array<LogTemplateResponseModel>;
};

export type PagedLoggerResponseModel = {
    total: number;
    items: Array<LoggerResponseModel>;
};

export type PagedMediaCollectionResponseModel = {
    total: number;
    items: Array<MediaCollectionResponseModel>;
};

export type PagedMediaRecycleBinItemResponseModel = {
    total: number;
    items: Array<MediaRecycleBinItemResponseModel>;
};

export type PagedMediaTreeItemResponseModel = {
    total: number;
    items: Array<MediaTreeItemResponseModel>;
};

export type PagedMediaTypeTreeItemResponseModel = {
    total: number;
    items: Array<MediaTypeTreeItemResponseModel>;
};

export type PagedMemberGroupResponseModel = {
    total: number;
    items: Array<MemberGroupResponseModel>;
};

export type PagedMemberResponseModel = {
    total: number;
    items: Array<MemberResponseModel>;
};

export type PagedMemberTypeTreeItemResponseModel = {
    total: number;
    items: Array<MemberTypeTreeItemResponseModel>;
};

export type PagedModelDataTypeItemResponseModel = {
    items: Array<DataTypeItemResponseModel>;
    total: number;
};

export type PagedModelDocumentItemResponseModel = {
    items: Array<DocumentItemResponseModel>;
    total: number;
};

export type PagedModelDocumentTypeItemResponseModel = {
    items: Array<DocumentTypeItemResponseModel>;
    total: number;
};

export type PagedModelMediaItemResponseModel = {
    items: Array<MediaItemResponseModel>;
    total: number;
};

export type PagedModelMediaTypeItemResponseModel = {
    items: Array<MediaTypeItemResponseModel>;
    total: number;
};

export type PagedModelMemberItemResponseModel = {
    items: Array<MemberItemResponseModel>;
    total: number;
};

export type PagedModelMemberTypeItemResponseModel = {
    items: Array<MemberTypeItemResponseModel>;
    total: number;
};

export type PagedModelTemplateItemResponseModel = {
    items: Array<TemplateItemResponseModel>;
    total: number;
};

export type PagedNamedEntityTreeItemResponseModel = {
    total: number;
    items: Array<NamedEntityTreeItemResponseModel>;
};

export type PagedObjectTypeResponseModel = {
    total: number;
    items: Array<ObjectTypeResponseModel>;
};

export type PagedPackageDefinitionResponseModelReadable = {
    total: number;
    items: Array<PackageDefinitionResponseModelReadable>;
};

export type PagedPackageDefinitionResponseModelWritable = {
    total: number;
    items: Array<PackageDefinitionResponseModelWritable>;
};

export type PagedPackageMigrationStatusResponseModel = {
    total: number;
    items: Array<PackageMigrationStatusResponseModel>;
};

export type PagedPartialViewSnippetItemResponseModel = {
    total: number;
    items: Array<PartialViewSnippetItemResponseModel>;
};

export type PagedProblemDetailsModel = {
    total: number;
    items: Array<ProblemDetails>;
};

export type PagedRedirectUrlResponseModel = {
    total: number;
    items: Array<RedirectUrlResponseModel>;
};

export type PagedReferenceByIdModel = {
    total: number;
    items: Array<ReferenceByIdModel>;
};

export type PagedRelationResponseModelReadable = {
    total: number;
    items: Array<RelationResponseModelReadable>;
};

export type PagedRelationResponseModelWritable = {
    total: number;
    items: Array<RelationResponseModelWritable>;
};

export type PagedRelationTypeResponseModel = {
    total: number;
    items: Array<RelationTypeResponseModel>;
};

export type PagedSavedLogSearchResponseModel = {
    total: number;
    items: Array<SavedLogSearchResponseModel>;
};

export type PagedSearchResultResponseModelReadable = {
    total: number;
    items: Array<SearchResultResponseModelReadable>;
};

export type PagedSearchResultResponseModelWritable = {
    total: number;
    items: Array<SearchResultResponseModelWritable>;
};

export type PagedSearcherResponseModel = {
    total: number;
    items: Array<SearcherResponseModel>;
};

export type PagedSegmentResponseModel = {
    total: number;
    items: Array<SegmentResponseModel>;
};

export type PagedTagResponseModel = {
    total: number;
    items: Array<TagResponseModel>;
};

export type PagedTelemetryResponseModel = {
    total: number;
    items: Array<TelemetryResponseModel>;
};

export type PagedUserDataResponseModel = {
    total: number;
    items: Array<UserDataResponseModel>;
};

export type PagedUserGroupResponseModel = {
    total: number;
    items: Array<UserGroupResponseModel>;
};

export type PagedUserResponseModel = {
    total: number;
    items: Array<UserResponseModel>;
};

export type PagedWebhookEventModel = {
    total: number;
    items: Array<WebhookEventModel>;
};

export type PagedWebhookLogResponseModel = {
    total: number;
    items: Array<WebhookLogResponseModel>;
};

export type PagedWebhookResponseModel = {
    total: number;
    items: Array<WebhookResponseModel>;
};

export type PartialViewFolderResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
};

export type PartialViewItemResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
    isFolder: boolean;
};

export type PartialViewResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
    content: string;
};

export type PartialViewSnippetItemResponseModel = {
    id: string;
    name: string;
};

export type PartialViewSnippetResponseModel = {
    id: string;
    name: string;
    content: string;
};

export type PasswordConfigurationResponseModel = {
    minimumPasswordLength: number;
    requireNonLetterOrDigit: boolean;
    requireDigit: boolean;
    requireLowercase: boolean;
    requireUppercase: boolean;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type ProblemDetailsBuilderModel = {
    [key: string]: never;
};

export type ProfilingStatusRequestModel = {
    enabled: boolean;
};

export type ProfilingStatusResponseModel = {
    enabled: boolean;
};

export type PropertyTypeAppearanceModel = {
    labelOnTop: boolean;
};

export type PropertyTypeValidationModel = {
    mandatory: boolean;
    mandatoryMessage?: string | null;
    regEx?: string | null;
    regExMessage?: string | null;
};

export type PublicAccessRequestModel = {
    loginDocument: ReferenceByIdModel;
    errorDocument: ReferenceByIdModel;
    memberUserNames: Array<string>;
    memberGroupNames: Array<string>;
};

export type PublicAccessResponseModel = {
    loginDocument: ReferenceByIdModel;
    errorDocument: ReferenceByIdModel;
    members: Array<MemberItemResponseModel>;
    groups: Array<MemberGroupItemResponseModel>;
};

export type PublishDocumentRequestModel = {
    publishSchedules: Array<CultureAndScheduleRequestModel>;
};

export type PublishDocumentWithDescendantsRequestModel = {
    includeUnpublishedDescendants: boolean;
    cultures: Array<string>;
};

export type PublishWithDescendantsResultModel = {
    taskId: string;
    isComplete: boolean;
};

export type PublishedDocumentResponseModel = {
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
    id: string;
    documentType: DocumentTypeReferenceResponseModel;
    /**
     * @deprecated
     */
    urls: Array<DocumentUrlInfoModel>;
    template?: ReferenceByIdModel | null;
    isTrashed: boolean;
};

export type RebuildStatusModel = {
    isRebuilding: boolean;
};

export enum RedirectStatusModel {
    ENABLED = 'Enabled',
    DISABLED = 'Disabled'
}

export type RedirectUrlResponseModel = {
    id: string;
    originalUrl: string;
    destinationUrl: string;
    created: string;
    document: ReferenceByIdModel;
    culture?: string | null;
};

export type RedirectUrlStatusResponseModel = {
    status: RedirectStatusModel;
    userIsAdmin: boolean;
};

export type ReferenceByIdModel = {
    id: string;
};

export type ReferencedEntityModel = {
    id?: number | null;
    changed?: string | null;
    title?: string | null;
    link?: string | null;
};

export type ReferencedLinkModel = {
    title?: string | null;
    link?: string | null;
};

export type RelationReferenceModel = {
    id: string;
    name?: string | null;
};

export type RelationResponseModelReadable = {
    id: string;
    relationType: ReferenceByIdModel;
    parent: RelationReferenceModel;
    child: RelationReferenceModel;
    readonly createDate: string;
    readonly comment?: string | null;
};

export type RelationResponseModelWritable = {
    id: string;
    relationType: ReferenceByIdModel;
    parent: RelationReferenceModel;
    child: RelationReferenceModel;
};

export type RelationTypeItemResponseModel = {
    id: string;
    name: string;
    isDeletable: boolean;
};

export type RelationTypeResponseModel = {
    name: string;
    isBidirectional: boolean;
    isDependency: boolean;
    id: string;
    alias?: string | null;
    parentObject?: ObjectTypeResponseModel | null;
    childObject?: ObjectTypeResponseModel | null;
};

export type RenamePartialViewRequestModel = {
    name: string;
};

export type RenameScriptRequestModel = {
    name: string;
};

export type RenameStylesheetRequestModel = {
    name: string;
};

export type ResendInviteUserRequestModel = {
    user: ReferenceByIdModel;
    message?: string | null;
};

export type ResetPasswordRequestModel = {
    email: string;
};

export type ResetPasswordTokenRequestModel = {
    user: ReferenceByIdModel;
    resetCode: string;
    password: string;
};

export type ResetPasswordUserResponseModel = {
    resetPassword?: string | null;
};

export enum RuntimeLevelModel {
    UNKNOWN = 'Unknown',
    BOOT = 'Boot',
    INSTALL = 'Install',
    UPGRADE = 'Upgrade',
    RUN = 'Run',
    BOOT_FAILED = 'BootFailed'
}

export enum RuntimeModeModel {
    BACKOFFICE_DEVELOPMENT = 'BackofficeDevelopment',
    DEVELOPMENT = 'Development',
    PRODUCTION = 'Production'
}

export type SavedLogSearchRequestModel = {
    name: string;
    query: string;
};

export type SavedLogSearchResponseModel = {
    name: string;
    query: string;
};

export type ScheduleRequestModel = {
    publishTime?: string | null;
    unpublishTime?: string | null;
};

export type ScriptFolderResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
};

export type ScriptItemResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
    isFolder: boolean;
};

export type ScriptResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
    content: string;
};

export type SearchResultResponseModelReadable = {
    id: string;
    score: number;
    readonly fieldCount: number;
    fields: Array<FieldPresentationModel>;
};

export type SearchResultResponseModelWritable = {
    id: string;
    score: number;
    fields: Array<FieldPresentationModel>;
};

export type SearcherResponseModel = {
    name: string;
};

export type SecurityConfigurationResponseModel = {
    passwordConfiguration: PasswordConfigurationResponseModel;
};

export type SegmentResponseModel = {
    name: string;
    alias: string;
};

export type ServerConfigurationItemResponseModel = {
    name: string;
    data: string;
};

export type ServerConfigurationResponseModel = {
    allowPasswordReset: boolean;
    versionCheckPeriod: number;
    allowLocalLogin: boolean;
};

export type ServerInformationResponseModel = {
    version: string;
    assemblyVersion: string;
    baseUtcOffset: string;
    runtimeMode: RuntimeModeModel;
};

export type ServerStatusResponseModel = {
    serverStatus: RuntimeLevelModel;
};

export type ServerTroubleshootingResponseModel = {
    items: Array<ServerConfigurationItemResponseModel>;
};

export type SetAvatarRequestModel = {
    file: ReferenceByIdModel;
};

export enum SituationContentTypeModel {
    TEXT = 'Text',
    VIDEO = 'Video',
    DECISION_AID = 'Decision_Aid',
    CONSULTATION_CARD = 'Consultation_Card',
    RESEARCH = 'Research'
}

export type SituationModel = {
    id?: number | null;
    uuid?: string | null;
    changed?: string | null;
    revision_date?: string | null;
    title?: string | null;
    link?: string | null;
    subject?: ReferencedEntityModel | null;
    content?: Array<ContentSituationModel> | null;
    codes?: CodesModel | null;
    related?: SituationRelatedModel | null;
};

export type SituationRelatedModel = {
    situations?: Array<ReferencedEntityModel> | null;
    links?: Array<ReferencedLinkModel> | null;
};

export type SortingRequestModel = {
    parent?: ReferenceByIdModel | null;
    sorting: Array<ItemSortingRequestModel>;
};

export type StaticFileItemResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
    isFolder: boolean;
};

export enum StatusResultTypeModel {
    SUCCESS = 'Success',
    WARNING = 'Warning',
    ERROR = 'Error',
    INFO = 'Info'
}

export type StylesheetFolderResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
};

export type StylesheetItemResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
    isFolder: boolean;
};

export type StylesheetResponseModel = {
    path: string;
    name: string;
    parent?: FileSystemFolderModel | null;
    content: string;
};

export type TagResponseModel = {
    id: string;
    text?: string | null;
    group?: string | null;
    nodeCount: number;
};

export enum TelemetryLevelModel {
    MINIMAL = 'Minimal',
    BASIC = 'Basic',
    DETAILED = 'Detailed'
}

export type TelemetryRequestModel = {
    telemetryLevel: TelemetryLevelModel;
};

export type TelemetryResponseModel = {
    telemetryLevel: TelemetryLevelModel;
};

export type TemplateConfigurationResponseModel = {
    disabled: boolean;
};

export type TemplateItemResponseModel = {
    id: string;
    name: string;
    alias: string;
};

export type TemplateQueryExecuteFilterPresentationModel = {
    propertyAlias: string;
    constraintValue: string;
    operator: OperatorModel;
};

export type TemplateQueryExecuteModel = {
    rootDocument?: ReferenceByIdModel | null;
    documentTypeAlias?: string | null;
    filters?: Array<TemplateQueryExecuteFilterPresentationModel> | null;
    sort?: TemplateQueryExecuteSortModel | null;
    take: number;
};

export type TemplateQueryExecuteSortModel = {
    propertyAlias: string;
    direction?: string | null;
};

export type TemplateQueryOperatorModel = {
    operator: OperatorModel;
    applicableTypes: Array<TemplateQueryPropertyTypeModel>;
};

export type TemplateQueryPropertyPresentationModel = {
    alias: string;
    type: TemplateQueryPropertyTypeModel;
};

export enum TemplateQueryPropertyTypeModel {
    STRING = 'String',
    DATE_TIME = 'DateTime',
    INTEGER = 'Integer'
}

export type TemplateQueryResultItemPresentationModel = {
    icon: string;
    name: string;
};

export type TemplateQueryResultResponseModel = {
    queryExpression: string;
    sampleResults: Array<TemplateQueryResultItemPresentationModel>;
    resultCount: number;
    executionTime: number;
};

export type TemplateQuerySettingsResponseModel = {
    documentTypeAliases: Array<string>;
    properties: Array<TemplateQueryPropertyPresentationModel>;
    operators: Array<TemplateQueryOperatorModel>;
};

export type TemplateResponseModel = {
    name: string;
    alias: string;
    content?: string | null;
    id: string;
    masterTemplate?: ReferenceByIdModel | null;
};

export type TemporaryFileConfigurationResponseModel = {
    imageFileTypes: Array<string>;
    disallowedUploadedFilesExtensions: Array<string>;
    allowedUploadedFileExtensions: Array<string>;
    maxFileSize?: number | null;
};

export type TemporaryFileResponseModel = {
    id: string;
    availableUntil?: string | null;
    fileName: string;
};

export type TrackedReferenceDocumentTypeModel = {
    id: string;
    icon?: string | null;
    alias?: string | null;
    name?: string | null;
};

export type TrackedReferenceMediaTypeModel = {
    id: string;
    icon?: string | null;
    alias?: string | null;
    name?: string | null;
};

export type TrackedReferenceMemberTypeModel = {
    id: string;
    icon?: string | null;
    alias?: string | null;
    name?: string | null;
};

export type UnknownTypePermissionPresentationModel = {
    $type: string;
    verbs: Array<string>;
    context: string;
};

export type UnlockUsersRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type UnpublishDocumentRequestModel = {
    cultures?: Array<string> | null;
};

export type UpdateDataTypeRequestModel = {
    name: string;
    editorAlias: string;
    editorUiAlias: string;
    values: Array<DataTypePropertyPresentationModel>;
};

export type UpdateDictionaryItemRequestModel = {
    name: string;
    translations: Array<DictionaryItemTranslationModel>;
};

export type UpdateDocumentBlueprintRequestModel = {
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
};

export type UpdateDocumentNotificationsRequestModel = {
    subscribedActionIds: Array<string>;
};

export type UpdateDocumentRequestModel = {
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
    template?: ReferenceByIdModel | null;
};

export type UpdateDocumentTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type UpdateDocumentTypePropertyTypeRequestModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type UpdateDocumentTypeRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<UpdateDocumentTypePropertyTypeRequestModel>;
    containers: Array<UpdateDocumentTypePropertyTypeContainerRequestModel>;
    allowedTemplates: Array<ReferenceByIdModel>;
    defaultTemplate?: ReferenceByIdModel | null;
    cleanup: DocumentTypeCleanupModel;
    allowedDocumentTypes: Array<DocumentTypeSortModel>;
    compositions: Array<DocumentTypeCompositionModel>;
};

export type UpdateDomainsRequestModel = {
    defaultIsoCode?: string | null;
    domains: Array<DomainPresentationModel>;
};

export type UpdateFolderResponseModel = {
    name: string;
};

export type UpdateLanguageRequestModel = {
    name: string;
    isDefault: boolean;
    isMandatory: boolean;
    fallbackIsoCode?: string | null;
};

export type UpdateMediaRequestModel = {
    values: Array<MediaValueModel>;
    variants: Array<MediaVariantRequestModel>;
};

export type UpdateMediaTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type UpdateMediaTypePropertyTypeRequestModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type UpdateMediaTypeRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<UpdateMediaTypePropertyTypeRequestModel>;
    containers: Array<UpdateMediaTypePropertyTypeContainerRequestModel>;
    allowedMediaTypes: Array<MediaTypeSortModel>;
    compositions: Array<MediaTypeCompositionModel>;
};

export type UpdateMemberGroupRequestModel = {
    name: string;
};

export type UpdateMemberRequestModel = {
    values: Array<MemberValueModel>;
    variants: Array<MemberVariantRequestModel>;
    email: string;
    username: string;
    oldPassword?: string | null;
    newPassword?: string | null;
    groups?: Array<string> | null;
    isApproved: boolean;
    isLockedOut: boolean;
    isTwoFactorEnabled: boolean;
};

export type UpdateMemberTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name?: string | null;
    type: string;
    sortOrder: number;
};

export type UpdateMemberTypePropertyTypeRequestModel = {
    id: string;
    container?: ReferenceByIdModel | null;
    sortOrder: number;
    alias: string;
    name: string;
    description?: string | null;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
    isSensitive: boolean;
    visibility: MemberTypePropertyTypeVisibilityModel;
};

export type UpdateMemberTypeRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: ReferenceByIdModel | null;
    isElement: boolean;
    properties: Array<UpdateMemberTypePropertyTypeRequestModel>;
    containers: Array<UpdateMemberTypePropertyTypeContainerRequestModel>;
    compositions: Array<MemberTypeCompositionModel>;
};

export type UpdatePackageRequestModelReadable = {
    name: string;
    contentNodeId?: string | null;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
    readonly packagePath: string;
};

export type UpdatePackageRequestModelWritable = {
    name: string;
    contentNodeId?: string | null;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
};

export type UpdatePartialViewRequestModel = {
    content: string;
};

export type UpdateScriptRequestModel = {
    content: string;
};

export type UpdateStylesheetRequestModel = {
    content: string;
};

export type UpdateTemplateRequestModel = {
    name: string;
    alias: string;
    content?: string | null;
};

export type UpdateUserDataRequestModel = {
    group: string;
    identifier: string;
    value: string;
    key: string;
};

export type UpdateUserGroupRequestModel = {
    name: string;
    alias: string;
    icon?: string | null;
    sections: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    documentStartNode?: ReferenceByIdModel | null;
    documentRootAccess: boolean;
    mediaStartNode?: ReferenceByIdModel | null;
    mediaRootAccess: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<DocumentPermissionPresentationModel | DocumentPropertyValuePermissionPresentationModel | UnknownTypePermissionPresentationModel>;
};

export type UpdateUserGroupsOnUserRequestModel = {
    userIds: Array<ReferenceByIdModel>;
    userGroupIds: Array<ReferenceByIdModel>;
};

export type UpdateUserRequestModel = {
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
    languageIsoCode: string;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
};

export type UpdateWebhookRequestModel = {
    enabled: boolean;
    name?: string | null;
    description?: string | null;
    url: string;
    contentTypeKeys: Array<string>;
    headers: {
        [key: string]: string;
    };
    events: Array<string>;
};

export type UpgradeCheckResponseModel = {
    type: string;
    comment: string;
    url: string;
};

export type UpgradeSettingsResponseModelReadable = {
    currentState: string;
    newState: string;
    newVersion: string;
    oldVersion: string;
    readonly reportUrl: string;
};

export type UpgradeSettingsResponseModelWritable = {
    currentState: string;
    newState: string;
    newVersion: string;
    oldVersion: string;
};

export type UserConfigurationResponseModel = {
    canInviteUsers: boolean;
    usernameIsEmail: boolean;
    passwordConfiguration: PasswordConfigurationResponseModel;
    allowChangePassword: boolean;
    allowTwoFactor: boolean;
};

export type UserDataModel = {
    group: string;
    identifier: string;
    value: string;
};

export enum UserDataOperationStatusModel {
    SUCCESS = 'Success',
    NOT_FOUND = 'NotFound',
    USER_NOT_FOUND = 'UserNotFound',
    ALREADY_EXISTS = 'AlreadyExists'
}

export type UserDataResponseModel = {
    group: string;
    identifier: string;
    value: string;
    key: string;
};

export type UserExternalLoginProviderModel = {
    providerSchemeName: string;
    providerKey?: string | null;
    isLinkedOnUser: boolean;
    hasManualLinkingEnabled: boolean;
};

export type UserGroupItemResponseModel = {
    id: string;
    name: string;
    icon?: string | null;
    alias?: string | null;
};

export type UserGroupResponseModel = {
    name: string;
    alias: string;
    icon?: string | null;
    sections: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    documentStartNode?: ReferenceByIdModel | null;
    documentRootAccess: boolean;
    mediaStartNode?: ReferenceByIdModel | null;
    mediaRootAccess: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<DocumentPermissionPresentationModel | DocumentPropertyValuePermissionPresentationModel | UnknownTypePermissionPresentationModel>;
    id: string;
    isDeletable: boolean;
    aliasCanBeChanged: boolean;
};

export type UserInstallRequestModelReadable = {
    name: string;
    email: string;
    password: string;
    readonly subscribeToNewsletter: boolean;
};

export type UserInstallRequestModelWritable = {
    name: string;
    email: string;
    password: string;
};

export type UserItemResponseModel = {
    id: string;
    name: string;
    avatarUrls: Array<string>;
    kind: UserKindModel;
};

export enum UserKindModel {
    DEFAULT = 'Default',
    API = 'Api'
}

export enum UserOrderModel {
    USER_NAME = 'UserName',
    LANGUAGE = 'Language',
    NAME = 'Name',
    EMAIL = 'Email',
    ID = 'Id',
    CREATE_DATE = 'CreateDate',
    UPDATE_DATE = 'UpdateDate',
    IS_APPROVED = 'IsApproved',
    IS_LOCKED_OUT = 'IsLockedOut',
    LAST_LOGIN_DATE = 'LastLoginDate'
}

export type UserPermissionModel = {
    nodeKey: string;
    permissions: Array<string>;
};

export type UserPermissionsResponseModel = {
    permissions: Array<UserPermissionModel>;
};

export type UserResponseModel = {
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
    id: string;
    languageIsoCode?: string | null;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
    avatarUrls: Array<string>;
    state: UserStateModel;
    failedLoginAttempts: number;
    createDate: string;
    updateDate: string;
    lastLoginDate?: string | null;
    lastLockoutDate?: string | null;
    lastPasswordChangeDate?: string | null;
    isAdmin: boolean;
    kind: UserKindModel;
};

export type UserSettingsPresentationModel = {
    minCharLength: number;
    minNonAlphaNumericLength: number;
    consentLevels: Array<ConsentLevelPresentationModel>;
};

export enum UserStateModel {
    ACTIVE = 'Active',
    DISABLED = 'Disabled',
    LOCKED_OUT = 'LockedOut',
    INVITED = 'Invited',
    INACTIVE = 'Inactive',
    ALL = 'All'
}

export type UserTwoFactorProviderModel = {
    providerName: string;
    isEnabledOnUser: boolean;
};

export type ValidateUpdateDocumentRequestModel = {
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
    template?: ReferenceByIdModel | null;
    cultures?: Array<string> | null;
};

export type VariantItemResponseModel = {
    name: string;
    culture?: string | null;
};

export type VerifyInviteUserRequestModel = {
    user: ReferenceByIdModel;
    token: string;
};

export type VerifyInviteUserResponseModel = {
    passwordConfiguration: PasswordConfigurationResponseModel;
};

export type VerifyResetPasswordResponseModel = {
    passwordConfiguration: PasswordConfigurationResponseModel;
};

export type VerifyResetPasswordTokenRequestModel = {
    user: ReferenceByIdModel;
    resetCode: string;
};

export type VideoUrlsModel = {
    video?: string | null;
    audio?: string | null;
    srt?: string | null;
    vtt?: string | null;
    still?: string | null;
};

export type WebhookEventModel = {
    eventName: string;
    eventType: string;
    alias: string;
};

export type WebhookEventResponseModel = {
    eventName: string;
    eventType: string;
    alias: string;
};

export type WebhookItemResponseModel = {
    enabled: boolean;
    name: string;
    events: string;
    url: string;
    types: string;
};

export type WebhookLogResponseModel = {
    key: string;
    webhookKey: string;
    statusCode: string;
    isSuccessStatusCode: boolean;
    date: string;
    eventAlias: string;
    url: string;
    retryCount: number;
    requestHeaders: string;
    requestBody: string;
    responseHeaders: string;
    responseBody: string;
    exceptionOccured: boolean;
};

export type WebhookResponseModel = {
    enabled: boolean;
    name?: string | null;
    description?: string | null;
    url: string;
    contentTypeKeys: Array<string>;
    headers: {
        [key: string]: string;
    };
    id: string;
    events: Array<WebhookEventResponseModel>;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};