/** English (en) strings for the `umbraDesktop` area — launcher chrome, friendly app names, and group labels. */
export default {
  umbraDesktop: {
    // app names
    appContentEditor: 'Content editor',
    appMediaLibrary: 'Media library',
    appTranslation: 'Translation',
    appDocumentTypes: 'Document Types',
    appDataTypes: 'Data Types',
    appTemplates: 'Templates',
    appUsers: 'Users',
    appMembers: 'Members',
    appLogViewer: 'Log Viewer',
    appExamineManagement: 'Examine Management',
    appHealthCheck: 'Health Check',
    appProfiling: 'Profiling',
    appSettings: 'Settings',
    appPackages: 'Packages',
    appModelsBuilder: 'Models Builder',
    appWebhooks: 'Webhooks',
    appAdvancedContentPermissions: 'Content permissions',
    appAdvancedContentAccess: 'Content access',
    appAdvancedDocTypePermissions: 'Document Type permissions',
    appAdvancedDocTypeAccess: 'Document Type access',
    appAdvancedLibraryPermissions: 'Library permissions',
    appAdvancedLibraryAccess: 'Library access',
    appAdvancedElementTypePermissions: 'Element Type permissions',
    appAdvancedElementTypeAccess: 'Element Type access',
    appWorkflowTasks: 'Workflow tasks',
    appWorkflowSearch: 'Workflow search',
    appWorkflowReleaseSets: 'Release sets',
    appDeploy: 'Deploy',
    appDeployEnvironments: 'Deploy environments',
    appDeployStatus: 'Deploy status',
    appDeploySchema: 'Deploy schema',
    appDeployConfiguration: 'Deploy configuration',
    appEngageConfiguration: 'Engage configuration',
    appBackgroundJobs: 'Background Jobs',
    // window body: a registered app's element failed to load (app-host.element carries the same
    // English as its own fallback, for the case where this dictionary is what failed to load).
    appLoadFailed: 'This app could not be loaded.',
    // group labels
    groupEditing: 'Editing',
    groupWorkflow: 'Workflow',
    groupMarketingSales: 'Marketing and sales',
    groupDevelopment: 'Development',
    groupSynchronisation: 'Synchronisation',
    groupSecurity: 'Security',
    groupAdvancedSecurity: 'Advanced security',
    groupDiagnostics: 'Diagnostics',
    groupAutomation: 'Automation',
    groupAi: 'AI',
    groupSystem: 'System',
    groupGames: 'Games',
    groupMore: 'More',
    // header-app launcher
    launchDesktop: 'Open desktop',
    // launcher chrome
    openApps: 'Open apps',
    search: 'Search apps, tools and content…',
    favourites: 'Pinned',
    recent: 'Recent',
    pin: 'Pin to top',
    unpin: 'Unpin',
    desktopSettings: 'Desktop settings',
    // desktop settings — theme
    theme: 'Theme',
    themeDescription: 'Changes the look of the desktop, taskbar and windows. Your content stays the same.',
    themeHighContrast:
      "The backoffice is in high contrast. Window content follows it; the desktop keeps this theme's darkest palette.",
    // desktop settings — wallpaper
    wallpaper: 'Wallpaper',
    wallpaperNone: 'None (gradient)',
    wallpaperBuiltIn: 'Built-in image',
    wallpaperFromMedia: 'From the Media Library',
    wallpaperBuiltInImages: 'Built-in images',
    wallpaperMediaLibrary: 'Media library',
    wallpaperPickerTitle: 'Choose a wallpaper',
    wallpaperNotAnImage: 'That file cannot be used as a wallpaper. Pick an image.',
    logout: 'Log out',
    exitDesktop: 'Exit desktop',
    // exiting the desktop
    exitHeadline: 'Exit desktop mode',
    exitQuestion: 'Return to the classic Umbraco backoffice? Your open windows will be closed.',
    exitConfirm: 'Exit',
    exitStay: 'Stay',
    // unsaved changes
    unsavedChanges: 'Unsaved changes',
    exitUnsavedOne: 'One window has unsaved changes, which will be discarded.',
    exitUnsaved: '%0% windows have unsaved changes, which will be discarded.',
    exitConflictedSole: 'That window has also been changed by someone else.',
    exitConflictedOne: 'One of them has also been changed by someone else.',
    exitConflictedMany: '%0% of them have also been changed by someone else.',
    // changed, trashed or deleted underneath a window
    noticeChangedTitle: 'Someone else changed this while you were editing it',
    noticeChangedBody: 'Saving now replaces their version with yours.',
    noticeTrashedTitle: 'Someone moved this to the recycle bin',
    noticeTrashedBody:
      'Items in the recycle bin are read-only, so this window will stop accepting changes as soon as it reloads. Copy anything you need now, or ask someone to restore it.',
    noticeDeletedTitle: 'This no longer exists',
    noticeDeletedBody: 'Someone deleted it permanently.',
    noticeDeletedDirtyBody:
      'Someone deleted it permanently. Your unsaved changes cannot be saved, because there is nothing left to save them to. Copy anything you need before you close this window.',
    noticeKeepMine: 'Keep my changes',
    // Short enough to sit beside "Keep my changes" without the banner reading as clutter. The full
    // sentence is `noticeChangedBody`'s job, and repeating it on the button was a large part of why
    // the bar looked busy.
    noticeDiscardMine: 'Discard mine, load theirs',
    noticeCloseWindow: 'Close window',
    noticeKeepHeadline: 'Keep your changes?',
    noticeKeepQuestion:
      'When you save, the changes the other person made will be lost. This window will keep warning you until you save or discard.',
    noticeKeepConfirm: 'Keep my changes',
    noticeAcknowledged: 'Changed by someone else',
    discardConflictedHeadline: 'Close this window?',
    discardConflictedQuestion:
      'Closing is the safe option here: your unsaved changes are discarded and the version someone else saved is kept.',
    // Background Jobs app
    backgroundJobsIntro:
      'Every scheduled job Umbraco runs behind your site: publishing, webhooks, cleanups, and anything a package added. Nothing here can be started or stopped, it is a read-only view of what the CMS is doing on its own.',
    backgroundJobsName: 'Name',
    backgroundJobsPeriod: 'Every',
    backgroundJobsLastRun: 'Last run',
    backgroundJobsLastOutcome: 'Outcome',
    backgroundJobsNextRun: 'Next run',
    backgroundJobsRunsOn: 'Runs on',
    backgroundJobsKindDistributed: 'Distributed',
    backgroundJobsKindRecurring: 'Recurring',
    backgroundJobsDistributedNote:
      'Shared across every server. Each run is claimed by one server, and the schedule is stored in the database, so it survives a restart. Umbraco does not record how a run ended, so there is no outcome to show.',
    backgroundJobsRecurringNote:
      'Run by each server for itself. Umbraco stores nothing about them, so what you see here has been observed since this server started.',
    backgroundJobsJobCountOne: '1 job',
    backgroundJobsJobCount: '%0% jobs',
    backgroundJobsStateRunning: 'Running',
    backgroundJobsStateStale: 'Stale',
    backgroundJobsStateManual: 'Manual',
    backgroundJobsOutcomeUnavailable: 'Not recorded by Umbraco',
    backgroundJobsOutcomeNotObserved: 'Not since restart',
    backgroundJobsOutcomeSucceeded: 'Succeeded',
    backgroundJobsOutcomeFailed: 'Failed',
    backgroundJobsOutcomeIgnored: 'Skipped on this server',
    backgroundJobsNeverRun: 'Not since restart',
    backgroundJobsDueNow: 'Due now',
    backgroundJobsAnyServer: 'Any server',
    backgroundJobsRoleUnknown: 'Unknown role',
    backgroundJobsRoleSingle: 'Single server',
    backgroundJobsRoleSchedulingPublisher: 'Scheduling publisher',
    backgroundJobsRoleSubscriber: 'Subscriber',
    backgroundJobsMonitoringSince: 'Monitoring since %0%',
    backgroundJobsRefreshingEveryOne: 'Refreshing every second',
    backgroundJobsRefreshingEvery: 'Refreshing every %0% seconds',
    backgroundJobsIntervalOne: 'Every second',
    backgroundJobsInterval: 'Every %0% seconds',
    backgroundJobsChooseInterval: 'Choose how often this refreshes',
    backgroundJobsLoadFailed: 'Could not load background jobs.',
    backgroundJobsRetrying: 'Retrying automatically.',
    backgroundJobsRefreshFailed: 'The last refresh failed. Showing the previous result.',
    backgroundJobsEmpty: 'No background jobs are registered on this server.',
  },
};
