/** English (en) strings for the `umbraDesktop` area — launcher chrome, friendly app names, and group labels. */
export default {
  umbraDesktop: {
    // app names
    appContentEditor: 'Content editor',
    appMediaLibrary: 'Media library',
    appTranslation: 'Translation',
    appDocumentTypes: 'Document Types',
    appDataTypes: 'Data Types',
    appTemplates: 'Templates',
    appUsers: 'Users',
    appMembers: 'Members',
    appLogViewer: 'Log Viewer',
    appExamineManagement: 'Examine Management',
    appHealthCheck: 'Health Check',
    appProfiling: 'Profiling',
    appSettings: 'Settings',
    appPackages: 'Packages',
    appModelsBuilder: 'Models Builder',
    appWebhooks: 'Webhooks',
    // group labels
    groupEditing: 'Editing',
    groupDevelopment: 'Development',
    groupUsersMembers: 'Users & Members',
    groupDiagnostics: 'Diagnostics',
    groupSystem: 'System',
    groupGames: 'Games',
    groupMore: 'More',
    // header-app launcher
    launchDesktop: 'Open desktop',
    // launcher chrome
    openApps: 'Open apps',
    search: 'Search apps, tools and content…',
    favourites: 'Pinned',
    recent: 'Recent',
    pin: 'Pin to top',
    unpin: 'Unpin',
    desktopSettings: 'Desktop settings',
    // desktop settings — wallpaper
    wallpaper: 'Wallpaper',
    wallpaperNone: 'None (gradient)',
    wallpaperBuiltIn: 'Built-in image',
    wallpaperFromMedia: 'From the Media Library',
    wallpaperBuiltInImages: 'Built-in images',
    wallpaperMediaLibrary: 'Media library',
    wallpaperPickerTitle: 'Choose a wallpaper',
    wallpaperNotAnImage: 'That file cannot be used as a wallpaper. Pick an image.',
    logout: 'Log out',
    exitDesktop: 'Exit desktop',
  },
};
