/** English (en) strings for the `umbraDesktop` area — launcher chrome, friendly app names, and group labels. */
export default {
  umbraDesktop: {
    // app names
    appContentEditor: 'Content editor',
    appMediaLibrary: 'Media library',
    appTranslation: 'Translation',
    appDocumentTypes: 'Document Types',
    appDataTypes: 'Data Types',
    appTemplates: 'Templates',
    appUsers: 'Users',
    appMembers: 'Members',
    appLogViewer: 'Log Viewer',
    appExamineManagement: 'Examine Management',
    appHealthCheck: 'Health Check',
    appProfiling: 'Profiling',
    appSettings: 'Settings',
    appPackages: 'Packages',
    appModelsBuilder: 'Models Builder',
    appWebhooks: 'Webhooks',
    appAdvancedContentPermissions: 'Content permissions',
    appAdvancedContentAccess: 'Content access',
    appAdvancedDocTypePermissions: 'Document Type permissions',
    appAdvancedDocTypeAccess: 'Document Type access',
    appAdvancedLibraryPermissions: 'Library permissions',
    appAdvancedLibraryAccess: 'Library access',
    appAdvancedElementTypePermissions: 'Element Type permissions',
    appAdvancedElementTypeAccess: 'Element Type access',
    appBackgroundJobs: 'Background Jobs',
    // group labels
    groupEditing: 'Editing',
    groupDevelopment: 'Development',
    groupSynchronisation: 'Synchronisation',
    groupSecurity: 'Security',
    groupAdvancedSecurity: 'Advanced security',
    groupDiagnostics: 'Diagnostics',
    groupSystem: 'System',
    groupGames: 'Games',
    groupMore: 'More',
    // header-app launcher
    launchDesktop: 'Open desktop',
    // launcher chrome
    openApps: 'Open apps',
    search: 'Search apps, tools and content…',
    favourites: 'Pinned',
    recent: 'Recent',
    pin: 'Pin to top',
    unpin: 'Unpin',
    desktopSettings: 'Desktop settings',
    // desktop settings — theme
    theme: 'Theme',
    themeDescription: 'Changes the look of the desktop, taskbar and windows. Your content stays the same.',
    themeHighContrast:
      "The backoffice is in high contrast. Window content follows it; the desktop keeps this theme's darkest palette.",
    // desktop settings — wallpaper
    wallpaper: 'Wallpaper',
    wallpaperNone: 'None (gradient)',
    wallpaperBuiltIn: 'Built-in image',
    wallpaperFromMedia: 'From the Media Library',
    wallpaperBuiltInImages: 'Built-in images',
    wallpaperMediaLibrary: 'Media library',
    wallpaperPickerTitle: 'Choose a wallpaper',
    wallpaperNotAnImage: 'That file cannot be used as a wallpaper. Pick an image.',
    logout: 'Log out',
    exitDesktop: 'Exit desktop',
    // Background Jobs app
    backgroundJobsIntro:
      'Every scheduled job Umbraco runs behind your site: publishing, webhooks, cleanups, and anything a package added. Nothing here can be started or stopped, it is a read-only view of what the CMS is doing on its own.',
    backgroundJobsName: 'Name',
    backgroundJobsPeriod: 'Every',
    backgroundJobsLastRun: 'Last run',
    backgroundJobsLastOutcome: 'Outcome',
    backgroundJobsNextRun: 'Next run',
    backgroundJobsRunsOn: 'Runs on',
    backgroundJobsKindDistributed: 'Distributed',
    backgroundJobsKindRecurring: 'Recurring',
    backgroundJobsDistributedNote:
      'Shared across every server. Each run is claimed by one server, and the schedule is stored in the database, so it survives a restart. Umbraco does not record how a run ended, so there is no outcome to show.',
    backgroundJobsRecurringNote:
      'Run by each server for itself. Umbraco stores nothing about them, so what you see here has been observed since this server started.',
    backgroundJobsJobCountOne: '1 job',
    backgroundJobsJobCount: '%0% jobs',
    backgroundJobsStateRunning: 'Running',
    backgroundJobsStateStale: 'Stale',
    backgroundJobsStateManual: 'Manual',
    backgroundJobsOutcomeUnavailable: 'Not recorded by Umbraco',
    backgroundJobsOutcomeNotObserved: 'Not since restart',
    backgroundJobsOutcomeSucceeded: 'Succeeded',
    backgroundJobsOutcomeFailed: 'Failed',
    backgroundJobsOutcomeIgnored: 'Skipped on this server',
    backgroundJobsNeverRun: 'Not since restart',
    backgroundJobsDueNow: 'Due now',
    backgroundJobsAnyServer: 'Any server',
    backgroundJobsRoleUnknown: 'Unknown role',
    backgroundJobsRoleSingle: 'Single server',
    backgroundJobsRoleSchedulingPublisher: 'Scheduling publisher',
    backgroundJobsRoleSubscriber: 'Subscriber',
    backgroundJobsMonitoringSince: 'Monitoring since %0%',
    backgroundJobsRefreshingEveryOne: 'Refreshing every second',
    backgroundJobsRefreshingEvery: 'Refreshing every %0% seconds',
    backgroundJobsIntervalOne: 'Every second',
    backgroundJobsInterval: 'Every %0% seconds',
    backgroundJobsChooseInterval: 'Choose how often this refreshes',
    backgroundJobsLoadFailed: 'Could not load background jobs.',
    backgroundJobsRetrying: 'Retrying automatically.',
    backgroundJobsRefreshFailed: 'The last refresh failed. Showing the previous result.',
    backgroundJobsEmpty: 'No background jobs are registered on this server.',
  },
};
