/** Dutch (nl) strings for the `umbraDesktop` area — launcher chrome, friendly app names, and group labels. */
export default {
  umbraDesktop: {
    appContentEditor: 'Content-editor',
    appMediaLibrary: 'Mediabibliotheek',
    appTranslation: 'Vertaling',
    appDocumentTypes: 'Documenttypes',
    appDataTypes: 'Datatypes',
    appTemplates: 'Templates',
    appUsers: 'Gebruikers',
    appMembers: 'Leden',
    appLogViewer: 'Logboek',
    appExamineManagement: 'Examine-beheer',
    appHealthCheck: 'Gezondheidscontrole',
    appProfiling: 'Profilering',
    appSettings: 'Instellingen',
    appPackages: 'Pakketten',
    appModelsBuilder: 'Models Builder',
    appWebhooks: 'Webhooks',
    groupEditing: 'Bewerken',
    groupDevelopment: 'Ontwikkeling',
    groupUsersMembers: 'Gebruikers & leden',
    groupDiagnostics: 'Diagnostiek',
    groupSystem: 'Systeem',
    groupGames: 'Spellen',
    groupMore: 'Meer',
    launchDesktop: 'Bureaublad openen',
    openApps: 'Apps openen',
    search: 'Zoek apps, tools en content…',
    favourites: 'Vastgezet',
    recent: 'Recent',
    pin: 'Bovenaan vastzetten',
    unpin: 'Losmaken',
    desktopSettings: 'Bureaublad-instellingen',
    logout: 'Uitloggen',
    exitDesktop: 'Bureaublad verlaten',
  },
};
