/** Dutch (nl) strings for the `umbraDesktop` area — launcher chrome, friendly app names, and group labels. */
export default {
  umbraDesktop: {
    appContentEditor: 'Content-editor',
    appMediaLibrary: 'Mediabibliotheek',
    appTranslation: 'Vertaling',
    appDocumentTypes: 'Documenttypes',
    appDataTypes: 'Datatypes',
    appTemplates: 'Templates',
    appUsers: 'Gebruikers',
    appMembers: 'Leden',
    appLogViewer: 'Logboek',
    appExamineManagement: 'Examine-beheer',
    appHealthCheck: 'Gezondheidscontrole',
    appProfiling: 'Profilering',
    appSettings: 'Instellingen',
    appPackages: 'Pakketten',
    appModelsBuilder: 'Models Builder',
    appWebhooks: 'Webhooks',
    appAdvancedContentPermissions: 'Inhoudsmachtigingen',
    appAdvancedContentAccess: 'Inhoudstoegang',
    appAdvancedDocTypePermissions: 'Documenttype-machtigingen',
    appAdvancedDocTypeAccess: 'Documenttype-toegang',
    appAdvancedLibraryPermissions: 'Library-machtigingen',
    appAdvancedLibraryAccess: 'Library-toegang',
    appAdvancedElementTypePermissions: 'Elementtype-machtigingen',
    appAdvancedElementTypeAccess: 'Elementtype-toegang',
    appBackgroundJobs: 'Achtergrondtaken',
    groupEditing: 'Bewerken',
    groupDevelopment: 'Ontwikkeling',
    groupSynchronisation: 'Synchronisatie',
    groupSecurity: 'Beveiliging',
    groupAdvancedSecurity: 'Geavanceerde beveiliging',
    groupDiagnostics: 'Diagnostiek',
    groupSystem: 'Systeem',
    groupGames: 'Spellen',
    groupMore: 'Meer',
    launchDesktop: 'Bureaublad openen',
    openApps: 'Apps openen',
    search: 'Zoek apps, tools en content…',
    favourites: 'Vastgezet',
    recent: 'Recent',
    pin: 'Bovenaan vastzetten',
    unpin: 'Losmaken',
    desktopSettings: 'Bureaublad-instellingen',
    // desktop settings — theme
    theme: 'Thema',
    themeDescription: 'Verandert het uiterlijk van het bureaublad, de taakbalk en de vensters. Je content blijft hetzelfde.',
    themeHighContrast:
      'De backoffice staat op hoog contrast. De vensterinhoud volgt dat; het bureaublad houdt het donkerste palet van dit thema aan.',
    // desktop settings — wallpaper
    wallpaper: 'Achtergrond',
    wallpaperNone: 'Geen (verloop)',
    wallpaperBuiltIn: 'Meegeleverde afbeelding',
    wallpaperFromMedia: 'Uit de Media-bibliotheek',
    wallpaperBuiltInImages: 'Meegeleverde afbeeldingen',
    wallpaperMediaLibrary: 'Media-bibliotheek',
    wallpaperPickerTitle: 'Kies een achtergrond',
    wallpaperNotAnImage: 'Dit bestand kan niet als achtergrond worden gebruikt. Kies een afbeelding.',
    logout: 'Uitloggen',
    exitDesktop: 'Bureaublad verlaten',
    // Background Jobs app
    backgroundJobsIntro:
      'Alle geplande taken die Umbraco achter je site uitvoert: publiceren, webhooks, opschoningen, en alles wat een pakket heeft toegevoegd. Je kunt hier niets starten of stoppen, dit is een alleen-lezen overzicht van wat het CMS uit zichzelf doet.',
    backgroundJobsName: 'Naam',
    backgroundJobsPeriod: 'Elke',
    backgroundJobsLastRun: 'Laatste uitvoering',
    backgroundJobsLastOutcome: 'Resultaat',
    backgroundJobsNextRun: 'Volgende uitvoering',
    backgroundJobsRunsOn: 'Draait op',
    backgroundJobsKindDistributed: 'Gedistribueerd',
    backgroundJobsKindRecurring: 'Terugkerend',
    backgroundJobsDistributedNote:
      'Gedeeld over alle servers. Elke uitvoering wordt door één server geclaimd en het schema staat in de database, dus het overleeft een herstart. Umbraco legt niet vast hoe een uitvoering is afgelopen, dus er is geen resultaat om te tonen.',
    backgroundJobsRecurringNote:
      'Wordt door elke server voor zichzelf uitgevoerd. Umbraco slaat hier niets over op, dus wat je hier ziet is waargenomen sinds deze server is gestart.',
    backgroundJobsJobCountOne: '1 taak',
    backgroundJobsJobCount: '%0% taken',
    backgroundJobsStateRunning: 'Actief',
    backgroundJobsStateStale: 'Vastgelopen',
    backgroundJobsStateManual: 'Handmatig',
    backgroundJobsOutcomeUnavailable: 'Niet vastgelegd door Umbraco',
    backgroundJobsOutcomeNotObserved: 'Nog niet sinds herstart',
    backgroundJobsOutcomeSucceeded: 'Geslaagd',
    backgroundJobsOutcomeFailed: 'Mislukt',
    backgroundJobsOutcomeIgnored: 'Overgeslagen op deze server',
    backgroundJobsNeverRun: 'Nog niet sinds herstart',
    backgroundJobsDueNow: 'Nu aan de beurt',
    backgroundJobsAnyServer: 'Elke server',
    backgroundJobsRoleUnknown: 'Onbekende rol',
    backgroundJobsRoleSingle: 'Enkele server',
    backgroundJobsRoleSchedulingPublisher: 'Scheduling publisher',
    backgroundJobsRoleSubscriber: 'Subscriber',
    backgroundJobsMonitoringSince: 'Bewaakt sinds %0%',
    backgroundJobsRefreshingEveryOne: 'Ververst elke seconde',
    backgroundJobsRefreshingEvery: 'Ververst elke %0% seconden',
    backgroundJobsIntervalOne: 'Elke seconde',
    backgroundJobsInterval: 'Elke %0% seconden',
    backgroundJobsChooseInterval: 'Kies hoe vaak dit ververst',
    backgroundJobsLoadFailed: 'Achtergrondtaken konden niet worden geladen.',
    backgroundJobsRetrying: 'Wordt automatisch opnieuw geprobeerd.',
    backgroundJobsRefreshFailed: 'De laatste verversing is mislukt. Het vorige resultaat wordt getoond.',
    backgroundJobsEmpty: 'Er zijn geen achtergrondtaken geregistreerd op deze server.',
  },
};
