/**
 * Dutch (nl) strings for the `umbraDesktopEntertainment` area. Same keys as `en.ts`, same reasons.
 *
 * "Minesweeper" is left untranslated on purpose: the Dutch Windows shipped it as Mijnenveger, but
 * the name a player is looking for in a launcher is the one they know the game by, and in practice
 * that is the English one. The game's own words are translated, since those are read rather than
 * searched for. "Snake" is the same word in Dutch, so the question does not arise.
 */
export default {
  umbraDesktopEntertainment: {
    minesweeper: 'Minesweeper',
    minesweeperNewGame: 'Nieuw spel',
    minesweeperMinesLeft: 'Mijnen over',
    minesweeperElapsed: 'Seconden verstreken',
    minesweeperBoard: 'Mijnenveld',
    minesweeperWon: 'Geveegd.',
    minesweeperLost: 'Boem.',
    minesweeperClosed: 'gesloten',
    minesweeperFlagged: 'gemarkeerd',
    minesweeperMine: 'mijn',
    minesweeperEmpty: 'leeg',
    minesweeperEasy: 'Makkelijk',
    snake: 'Snake',
    snakeNewGame: 'Nieuw spel',
    snakeScore: 'Score',
    snakeBest: 'Record',
    snakeBoard: 'Snake-speelveld. Stuur met de pijltjestoetsen',
    snakeStart: 'Druk op een pijltjestoets om te beginnen',
    snakePaused: 'Gepauzeerd. Druk op spatie om verder te gaan',
    snakeOver: 'Game over. Druk op spatie om opnieuw te spelen',
    snakeWon: 'Je hebt het hele veld gevuld!',
    snakeClassic: 'Klassiek',
    snakeOpenLeaderboard: 'Ranglijst openen',
    solitaire: 'Solitaire',
    solitaireNewGame: 'Nieuw spel',
    solitaireSettings: 'Instellingen',
    solitaireScore: 'Score',
    solitaireTime: 'Tijd',
    solitaireMoves: 'Zetten',
    solitaireTable: 'Speeltafel',
    solitaireAutoFinish: 'Afmaken',
    solitaireWon: 'Gewonnen',
    solitairePlayAgain: 'Nog een keer',
    solitaireSettingsTitle: 'Instellingen',
    solitaireGame: 'Spel',
    solitaireDrawOne: 'Eén kaart pakken',
    solitaireDrawThree: 'Drie kaarten pakken',
    solitaireDrawNextGame: 'Een wijziging hier geldt vanaf je volgende spel.',
    solitaireCardBack: 'Achterkant',
    solitaireCardFaces: 'Voorkant',
    solitaireDone: 'Klaar',
    solitaireClose: 'Sluiten',
    solitaireBackTheme: 'Volgt het thema',
    solitaireBackRabbit: 'Rabbit',
    solitaireBackCodegarden: 'Codegarden',
    solitaireBackCodeCabin: 'CodeCabin',
    solitaireBackDutchUmbracoAlliance: 'Dutch Umbraco Alliance',
    solitaireFacesClassic: 'Klassiek',
    solitaireCardName: '{1}{0}',
    solitaireFaceDown: 'Dichte kaart',
    solitaireRank1: 'aas',
    solitaireRank11: 'boer',
    solitaireRank12: 'vrouw',
    solitaireRank13: 'heer',
    solitaireSuitS: 'schoppen',
    solitaireSuitH: 'harten',
    solitaireSuitD: 'ruiten',
    solitaireSuitC: 'klaveren',
    solitaireRule: 'Hoogste score wint, inclusief tijdbonus',
    solitaireBonus: 'incl. {0} tijdbonus',
    solitaireLeaderboard: 'Ranglijst',
    solitaireShowLeaderboard: 'Ranglijst tonen',
  },
};
