/**
 * Dutch (nl) strings for the `umbraDesktopArcade` area. Same keys as `en.ts`, same reasons.
 */
export default {
  umbraDesktopArcade: {
    groupGames: 'Spellen',
    // The hub (design P11, P12).
    hub: 'Arcade',
    needsDesktop: 'De Arcade werkt alleen op het bureaublad.',
    play: 'Spelen',
    allGames: 'Alle spellen',
    yourProfile: 'Je profiel',
    standLead: 'Ranglijsten die je leidt',
    standTopThree: 'Nog in je top drie',
    standColleagues: 'Collega’s die spelen',
    notPlayed: 'Nog niet gespeeld',
    next: 'Volgende: {0}',
    boardEmpty: 'Niemand heeft dit nog gespeeld.',
    boardUnavailable: 'De ranglijst kon niet worden geladen.',
    overviewUnavailable: 'De Arcade kon niet worden geladen.',
    retry: 'Opnieuw proberen',
    // How to win.
    ruleFastest: 'Snelste tijd wint',
    ruleHighest: 'Hoogste score wint',
    ruleLowest: 'Laagste score wint',
    ruleLongest: 'Langste tijd wint',
    // Ranks and numbers. Dutch has one ordinal form; `ordinalRules` as in en.ts.
    ordinalRules: 'nl',
    ordinalOne: '{0}e',
    ordinalTwo: '{0}e',
    ordinalFew: '{0}e',
    ordinalOther: '{0}e',
    unitSeconds: 'sec',
    unitPoints: 'punten',
    players: (count: number) => (count === 1 ? '1 speler' : `${count} spelers`),
    you: 'Jij',
    // The result card.
    outcomeWon: 'Gewonnen',
    outcomeOver: 'Game over',
    ribbonNewBest: 'Nieuw record',
    ribbonFirst: 'Eerste plaats',
    standing: '{0} van {1}',
    wouldBe: 'zou {0} zijn',
    yourBest: 'Je record {0}',
    stillLeads: 'Je record {0} staat nog bovenaan',
    passed: 'voorbij de {1} van {0}',
    chase: '{0} achter {1}',
    leaderboardLink: 'Ranglijst',
    playAgain: 'Nog een keer',
    // Showing and hiding scores. Never "privé", "openbaar" or "naam": wording.test.ts.
    askStanding: 'Dat is {0} van {1}.',
    ask: 'Je scores tonen op de Arcade-ranglijst, waar collega’s ze kunnen zien?',
    answerShow: 'Ja, toon mijn scores',
    answerHide: 'Nee, alleen ik zie ze',
    hiddenLine: 'Je scores zijn verborgen op de ranglijst.',
    showThemLink: 'Toon ze',
    onlyYou: 'Alleen jij ziet dit',
    fallbackHeadline: 'Je scores tonen op de Arcade-ranglijst?',
    fallbackText:
      'De Arcade bewaart ieders beste scores in de spellen op het bureaublad en zet ze op ranglijsten. Je scores daar tonen, waar collega’s ze kunnen zien? Je kunt dit altijd wijzigen in de Arcade.',
    // The panel.
    leaderboard: 'Ranglijst',
    openInArcade: 'Openen in de Arcade',
    close: 'Sluiten',
    // Toasts.
    newBest: 'Nieuw record op {0}: {1}',
    newBestRanked: 'Nieuw record op {0}: {1}, nummer {2}',
    beatenHeadline: '{0} heeft je de eerste plaats op {1} afgenomen',
    beatenScore: '{0} verslaat jouw {1}.',
    beatenRank: 'Je staat nu {0}.',
    beatenWith: 'Met {0}.',
    beatenOpen: 'Selecteer om de ranglijst te openen.',
    beatenOpenLink: 'Ranglijst openen',
    // The profile.
    leaderboardName: 'Je naam op de ranglijsten',
    leaderboardNameHelp: 'Wat collega’s naast je scores zien. Begint als je Umbraco-naam.',
    save: 'Opslaan',
    showScores: 'Mijn scores tonen op de ranglijsten',
    showScoresHelp: 'Uit: collega’s zien ze niet; je eigen plaats zie je nog wel.',
    notifyBeaten: 'Laat het me weten als iemand mijn eerste plaats overneemt',
    notifyBeatenHelp: 'Getoond de volgende keer dat je het bureaublad opent.',
    deleteMyScores: 'Mijn scores verwijderen',
    deleteHelp: 'Verwijdert al je scores en je naam uit de Arcade. Dit kan niet ongedaan worden gemaakt.',
    deleteHeadline: 'Je scores verwijderen?',
    deleteText: 'Je scores en Arcade-instellingen worden van elke ranglijst verwijderd. Dit kan niet ongedaan worden gemaakt.',
    delete: 'Verwijderen',
    saveFailed: 'Je wijzigingen konden niet worden opgeslagen.',
    deleteFailed: 'Je scores konden niet worden verwijderd.',
    // Moderation.
    moreActions: 'Meer acties voor {0}',
    removeScore: 'Score verwijderen',
    removeScoreHeadline: 'Deze score verwijderen?',
    remove: 'Verwijderen',
    resetName: 'Naam herstellen',
    resetNameHeadline: 'Deze naam herstellen?',
    resetNameText: 'De speler krijgt de Umbraco-naam terug: {0}',
    resetBoard: 'Deze ranglijst wissen',
    resetBoardHeadline: 'Deze ranglijst wissen?',
    resetBoardText: 'Alle scores erop worden verwijderd. Dit kan niet ongedaan worden gemaakt.',
    reset: 'Wissen',
    actionFailed: 'Dat is niet gelukt. Probeer het opnieuw.',
  },
};
