parameters:
- name: publishToProudNerdsNuGetFeed
  displayName: 'Publish to ProudNerds NuGet feed'
  type: boolean
  default: false

trigger: none

variables:
  # This name of the job as displayed in the pipeline on screen
  - name: jobDisplayName
    ${{ if eq(parameters['publishToProudNerdsNuGetFeed'], false) }}:
      value: "Building NuGet package"
    ${{ else }}:
      value: "Publishing NuGet package"
 
jobs:
- job: PublishSolutionJob
  displayName: "${{ variables.jobDisplayName }}"
  variables:
  - template: ../variables/variables.yml
  
  # The configuration to build the project in
  - name: buildConfiguration
    value: 'Release'
  
  # What version suffix to use for determining the package version
  - name: versionSuffix
    ${{ if contains(variables['Build.SourceBranch'], '/develop') }}:
      value: "beta$(Build.BuildNumber)"
    ${{ elseif contains(variables['Build.SourceBranch'], '/release/') }}:
      value: "rc$(Build.BuildNumber)"
    ${{ elseif contains(variables['Build.SourceBranch'], '/hotfix/') }}:
      value:  "hotfix$(Build.BuildNumber)"
    ${{ elseif contains(variables['Build.SourceBranch'], '/support/') }}:
      value:  ""
    ${{ elseif contains(variables['Build.SourceBranch'], '/main') }}:
      value:  ""
    ${{ else }}:
      value:  "unknownsource"
  
  # The arguments to use on the dotnet command (build/publish/pack etc)
  - name: dotnetArguments
    ${{ if variables.versionSuffix }}:
      value: "--version-suffix $(versionSuffix) --configuration $(buildConfiguration)"
    ${{ else }}:
      value: '--configuration $(buildConfiguration)'

  # The argument to use for the packagesToPack argument in the pack task
  - name: packagesToPackArgument
    ${{ if ne(variables.packagesToPackOverride, '') }}:
      value: "${{ variables.packagesToPackOverride }}"
    ${{ else }}:
       value: "src/**/*.csproj"       
  pool:
    vmImage: "${{ variables.image }}"
  steps:

  # Displaying variables for reference and debugging if required
  - script: echo "Source branch is ${{variables['Build.SourceBranch']}}, version suffix is $(versionSuffix), Buildnumber is $(Build.BuildNumber), packagesToPackArgument is ${{variables.packagesToPackArgument}}"
    displayName: Displaying variables for reference

  # Set .NET version if required
  - task: UseDotNet@2
    condition: ${{ ne(variables.dotNetVersion, '') }}
    displayName: '.NET: Use .NET ${{ variables.dotNetVersion }}'
    inputs:
      version: '${{ variables.dotNetVersion }}'
  
  # Authentication on the NuGet feed
  - task: NuGetAuthenticate@1
    displayName: NuGet authenticate without parameters

  # Run npm scripts if required
  - ${{ if ne(variables.npmScriptsToRun, '') }}:
    - ${{ each npmEntry in split(variables.npmScriptsToRun, ',') }}:
      - task: Npm@1
        displayName: "NPM: Install npm folder ${{ split(npmEntry, ':')[0] }}"
        inputs:
          command: 'ci'
          workingDir: "${{ split(npmEntry, ':')[0] }}"
          verbose: true
      - task: Npm@1
        displayName: 'NPM: run script'
        inputs:
          command: 'custom'
          workingDir: "${{ split(npmEntry, ':')[0] }}"
          customCommand: "run ${{split(npmEntry, ':')[1]}}"
          verbose: true

  # Remove source folders after npm build if configured, so they are not included in the NuGet package
  - ${{ if ne(variables.npmFoldersToRemove, '') }}:
    - ${{ each folder in split(variables.npmFoldersToRemove, ',') }}:
      - script: rm -rf "$(System.DefaultWorkingDirectory)/${{ folder }}"
        displayName: "Remove source folder after npm build: ${{ folder }}"
  
  # Build the project(s)
  - task: DotNetCoreCLI@2
    displayName: Build project
    inputs:
      command: 'build'
      configuration: '${{ variables.buildConfiguration}}'
      feedsToUse: 'select'
      vstsFeed: '${{ variables.internalNuGetFeedId }}'
      projects: '*.sln'
      arguments: '${{variables.dotnetArguments}}'

  # Run unit tests
  - ${{ if ne(variables.unitTestProjects, '') }}:
    - task: DotNetCoreCLI@2
      displayName: Run unit tests
      inputs:
        command: 'test'
        projects: '${{ variables.unitTestProjects }}'
        testRunTitle: 'Unit tests'


  # Pack all packable projects into NuGet package files
  - task: DotNetCoreCLI@2
    displayName: Pack into package file
    inputs:
      command: 'pack'
      packagesToPack: '${{variables.packagesToPackArgument}}'
      nobuild: true
      versioningScheme: 'off'
      arguments: '${{variables.dotnetArguments}}'

  # Push the NuGet package to the ProudNerds NuGet feed
  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(${{ parameters.publishToProudNerdsNuGetFeed }}, true))
    displayName: Push to internal NuGet
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '${{ variables.internalNuGetFeedId }}'

    # If the build is on a main branch (e.g. main, v13/main, v14/main), create a pull request back to the corresponding develop branch
  - task: PowerShell@2 
    condition: and(succeeded(), endsWith(variables['Build.SourceBranch'], '/main'))
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      RepositoryName: $(Build.Repository.Name)
      SourceBranch: $(Build.SourceBranch)
    displayName: Create pull request
    inputs:
      filePath: $(System.DefaultWorkingDirectory)/Solution files/Pipelines/scripts/auto-pull-request.ps1