// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Community.UmbraDesktop.Services.Arcade.Data;

#nullable disable

namespace Umbraco.Community.UmbraDesktop.Services.Arcade.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteArcadeDbContext))]
    [Migration("20261002142051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeBeatenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ByUserKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AtUtc");

                    b.HasIndex("ByUserKey");

                    b.HasIndex("UserKey", "Game", "Board")
                        .IsUnique();

                    b.ToTable("umbraDesktopArcadeBeaten", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeLeaderboardEntity", b =>
                {
                    b.Property<string>("Game")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Better")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Min")
                        .HasColumnType("INTEGER");

                    b.HasKey("Game", "Board");

                    b.ToTable("umbraDesktopArcadeLeaderboard", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeProfileEntity", b =>
                {
                    b.Property<Guid>("UserKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AskedAboutPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyWhenBeaten")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserKey");

                    b.ToTable("umbraDesktopArcadeProfile", (string)null);
                });

            modelBuilder.Entity("Umbraco.Community.UmbraDesktop.Services.Arcade.Data.ArcadeScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AchievedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Game", "Board");

                    b.HasIndex("UserKey", "Game", "Board")
                        .IsUnique();

                    b.ToTable("umbraDesktopArcadeScore", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
